/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.origami.sigef.common.controller;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import org.primefaces.barcelona.domain.Document;

/**
 *
 * @author Angel Navarro
 */
@Named
@ApplicationScoped
public class IconService {

    private List<Document> icons;
    private List<Document> faIcons;

    @PostConstruct
    public void createIcons() {
        icons = new ArrayList<>();
        icons.add(new Document("3d-rotation"));
        icons.add(new Document("ac-unit"));
        icons.add(new Document("access-alarm"));
        icons.add(new Document("access-alarms"));
        icons.add(new Document("access-time"));
        icons.add(new Document("accessibility"));
        icons.add(new Document("accessible"));
        icons.add(new Document("account-balance"));
        icons.add(new Document("account-balance-wallet"));
        icons.add(new Document("account-box"));
        icons.add(new Document("account-circle"));
        icons.add(new Document("adb"));
        icons.add(new Document("add"));
        icons.add(new Document("add-a-photo"));
        icons.add(new Document("add-alarm"));
        icons.add(new Document("add-alert"));
        icons.add(new Document("add-box"));
        icons.add(new Document("add-circle"));
        icons.add(new Document("add-circle-outline"));
        icons.add(new Document("add-location"));
        icons.add(new Document("add-shopping-cart"));
        icons.add(new Document("add-to-photos"));
        icons.add(new Document("add-to-queue"));
        icons.add(new Document("adjust"));
        icons.add(new Document("airline-seat-flat"));
        icons.add(new Document("airline-seat-flat-angled"));
        icons.add(new Document("airline-seat-individual-suite"));
        icons.add(new Document("airline-seat-legroom-extra"));
        icons.add(new Document("airline-seat-legroom-normal"));
        icons.add(new Document("airline-seat-legroom-reduced"));
        icons.add(new Document("airline-seat-recline-extra"));
        icons.add(new Document("airline-seat-recline-normal"));
        icons.add(new Document("airplanemode-active"));
        icons.add(new Document("airplanemode-inactive"));
        icons.add(new Document("airplay"));
        icons.add(new Document("airport-shuttle"));
        icons.add(new Document("alarm"));
        icons.add(new Document("alarm-add"));
        icons.add(new Document("alarm-off"));
        icons.add(new Document("alarm-on"));
        icons.add(new Document("album"));
        icons.add(new Document("all-inclusive"));
        icons.add(new Document("all-out"));
        icons.add(new Document("android"));
        icons.add(new Document("announcement"));
        icons.add(new Document("apps"));
        icons.add(new Document("archive"));
        icons.add(new Document("arrow-back"));
        icons.add(new Document("arrow-downward"));
        icons.add(new Document("arrow-drop-down"));
        icons.add(new Document("arrow-drop-down-circle"));
        icons.add(new Document("arrow-drop-up"));
        icons.add(new Document("arrow-forward"));
        icons.add(new Document("arrow-upward"));
        icons.add(new Document("art-track"));
        icons.add(new Document("aspect-ratio"));
        icons.add(new Document("assessment"));
        icons.add(new Document("assignment"));
        icons.add(new Document("assignment-ind"));
        icons.add(new Document("assignment-late"));
        icons.add(new Document("assignment-return"));
        icons.add(new Document("assignment-returned"));
        icons.add(new Document("assignment-turned-in"));
        icons.add(new Document("assistant"));
        icons.add(new Document("assistant-photo"));
        icons.add(new Document("attach-file"));
        icons.add(new Document("attach-money"));
        icons.add(new Document("attachment"));
        icons.add(new Document("audiotrack"));
        icons.add(new Document("autorenew"));
        icons.add(new Document("av-timer"));
        icons.add(new Document("backspace"));
        icons.add(new Document("backup"));
        icons.add(new Document("battery-alert"));
        icons.add(new Document("battery-charging-full"));
        icons.add(new Document("battery-full"));
        icons.add(new Document("battery-std"));
        icons.add(new Document("battery-unknown"));
        icons.add(new Document("beach-access"));
        icons.add(new Document("beenhere"));
        icons.add(new Document("block"));
        icons.add(new Document("bluetooth"));
        icons.add(new Document("bluetooth-audio"));
        icons.add(new Document("bluetooth-connected"));
        icons.add(new Document("bluetooth-disabled"));
        icons.add(new Document("bluetooth-searching"));
        icons.add(new Document("blur-circular"));
        icons.add(new Document("blur-linear"));
        icons.add(new Document("blur-off"));
        icons.add(new Document("blur-on"));
        icons.add(new Document("book"));
        icons.add(new Document("bookmark"));
        icons.add(new Document("bookmark-border"));
        icons.add(new Document("border-all"));
        icons.add(new Document("border-bottom"));
        icons.add(new Document("border-clear"));
        icons.add(new Document("border-color"));
        icons.add(new Document("border-horizontal"));
        icons.add(new Document("border-inner"));
        icons.add(new Document("border-left"));
        icons.add(new Document("border-outer"));
        icons.add(new Document("border-right"));
        icons.add(new Document("border-style"));
        icons.add(new Document("border-top"));
        icons.add(new Document("border-vertical"));
        icons.add(new Document("branding-watermark"));
        icons.add(new Document("brightness-1"));
        icons.add(new Document("brightness-2"));
        icons.add(new Document("brightness-3"));
        icons.add(new Document("brightness-4"));
        icons.add(new Document("brightness-5"));
        icons.add(new Document("brightness-6"));
        icons.add(new Document("brightness-7"));
        icons.add(new Document("brightness-auto"));
        icons.add(new Document("brightness-high"));
        icons.add(new Document("brightness-low"));
        icons.add(new Document("brightness-medium"));
        icons.add(new Document("broken-image"));
        icons.add(new Document("brush"));
        icons.add(new Document("bubble-chart"));
        icons.add(new Document("bug-report"));
        icons.add(new Document("build"));
        icons.add(new Document("burst-mode"));
        icons.add(new Document("business"));
        icons.add(new Document("business-center"));
        icons.add(new Document("cached"));
        icons.add(new Document("cake"));
        icons.add(new Document("call"));
        icons.add(new Document("call-end"));
        icons.add(new Document("call-made"));
        icons.add(new Document("call-merge"));
        icons.add(new Document("call-missed"));
        icons.add(new Document("call-missed-outgoing"));
        icons.add(new Document("call-received"));
        icons.add(new Document("call-split"));
        icons.add(new Document("call-to-action"));
        icons.add(new Document("camera"));
        icons.add(new Document("camera-alt"));
        icons.add(new Document("camera-enhance"));
        icons.add(new Document("camera-front"));
        icons.add(new Document("camera-rear"));
        icons.add(new Document("camera-roll"));
        icons.add(new Document("cancel"));
        icons.add(new Document("card-giftcard"));
        icons.add(new Document("card-membership"));
        icons.add(new Document("card-travel"));
        icons.add(new Document("casino"));
        icons.add(new Document("cast"));
        icons.add(new Document("cast-connected"));
        icons.add(new Document("center-focus-strong"));
        icons.add(new Document("center-focus-weak"));
        icons.add(new Document("change-history"));
        icons.add(new Document("chat"));
        icons.add(new Document("chat-bubble"));
        icons.add(new Document("chat-bubble-outline"));
        icons.add(new Document("check"));
        icons.add(new Document("check-box"));
        icons.add(new Document("check-box-outline-blank"));
        icons.add(new Document("check-circle"));
        icons.add(new Document("chevron-left"));
        icons.add(new Document("chevron-right"));
        icons.add(new Document("child-care"));
        icons.add(new Document("child-friendly"));
        icons.add(new Document("chrome-reader-mode"));
        icons.add(new Document("class"));
        icons.add(new Document("clear"));
        icons.add(new Document("clear-all"));
        icons.add(new Document("close"));
        icons.add(new Document("closed-caption"));
        icons.add(new Document("cloud"));
        icons.add(new Document("cloud-circle"));
        icons.add(new Document("cloud-done"));
        icons.add(new Document("cloud-download"));
        icons.add(new Document("cloud-off"));
        icons.add(new Document("cloud-queue"));
        icons.add(new Document("cloud-upload"));
        icons.add(new Document("code"));
        icons.add(new Document("collections"));
        icons.add(new Document("collections-bookmark"));
        icons.add(new Document("color-lens"));
        icons.add(new Document("colorize"));
        icons.add(new Document("comment"));
        icons.add(new Document("compare"));
        icons.add(new Document("compare-arrows"));
        icons.add(new Document("computer"));
        icons.add(new Document("confirmation-number"));
        icons.add(new Document("contact-mail"));
        icons.add(new Document("contact-phone"));
        icons.add(new Document("contacts"));
        icons.add(new Document("content-copy"));
        icons.add(new Document("content-cut"));
        icons.add(new Document("content-paste"));
        icons.add(new Document("control-point"));
        icons.add(new Document("control-point-duplicate"));
        icons.add(new Document("copyright"));
        icons.add(new Document("create"));
        icons.add(new Document("create-new-folder"));
        icons.add(new Document("credit-card"));
        icons.add(new Document("crop"));
        icons.add(new Document("crop-16-9"));
        icons.add(new Document("crop-3-2"));
        icons.add(new Document("crop-5-4"));
        icons.add(new Document("crop-7-5"));
        icons.add(new Document("crop-din"));
        icons.add(new Document("crop-free"));
        icons.add(new Document("crop-landscape"));
        icons.add(new Document("crop-original"));
        icons.add(new Document("crop-portrait"));
        icons.add(new Document("crop-rotate"));
        icons.add(new Document("crop-square"));
        icons.add(new Document("dashboard"));
        icons.add(new Document("data-usage"));
        icons.add(new Document("date-range"));
        icons.add(new Document("dehaze"));
        icons.add(new Document("delete"));
        icons.add(new Document("delete-forever"));
        icons.add(new Document("delete-sweep"));
        icons.add(new Document("description"));
        icons.add(new Document("desktop-mac"));
        icons.add(new Document("desktop-windows"));
        icons.add(new Document("details"));
        icons.add(new Document("developer-board"));
        icons.add(new Document("developer-mode"));
        icons.add(new Document("device-hub"));
        icons.add(new Document("devices"));
        icons.add(new Document("devices-other"));
        icons.add(new Document("dialer-sip"));
        icons.add(new Document("dialpad"));
        icons.add(new Document("directions"));
        icons.add(new Document("directions-bike"));
        icons.add(new Document("directions-boat"));
        icons.add(new Document("directions-bus"));
        icons.add(new Document("directions-car"));
        icons.add(new Document("directions-railway"));
        icons.add(new Document("directions-run"));
        icons.add(new Document("directions-subway"));
        icons.add(new Document("directions-transit"));
        icons.add(new Document("directions-walk"));
        icons.add(new Document("disc-full"));
        icons.add(new Document("dns"));
        icons.add(new Document("do-not-disturb"));
        icons.add(new Document("do-not-disturb-alt"));
        icons.add(new Document("do-not-disturb-off"));
        icons.add(new Document("do-not-disturb-on"));
        icons.add(new Document("dock"));
        icons.add(new Document("domain"));
        icons.add(new Document("done"));
        icons.add(new Document("done-all"));
        icons.add(new Document("donut-large"));
        icons.add(new Document("donut-small"));
        icons.add(new Document("drafts"));
        icons.add(new Document("drag-handle"));
        icons.add(new Document("drive-eta"));
        icons.add(new Document("dvr"));
        icons.add(new Document("edit"));
        icons.add(new Document("edit-location"));
        icons.add(new Document("eject"));
        icons.add(new Document("email"));
        icons.add(new Document("enhanced-encryption"));
        icons.add(new Document("equalizer"));
        icons.add(new Document("error"));
        icons.add(new Document("error-outline"));
        icons.add(new Document("euro-symbol"));
        icons.add(new Document("ev-station"));
        icons.add(new Document("event"));
        icons.add(new Document("event-available"));
        icons.add(new Document("event-busy"));
        icons.add(new Document("event-note"));
        icons.add(new Document("event-seat"));
        icons.add(new Document("exit-to-app"));
        icons.add(new Document("expand-less"));
        icons.add(new Document("expand-more"));
        icons.add(new Document("explicit"));
        icons.add(new Document("explore"));
        icons.add(new Document("exposure"));
        icons.add(new Document("exposure-neg-1"));
        icons.add(new Document("exposure-neg-2"));
        icons.add(new Document("exposure-plus-1"));
        icons.add(new Document("exposure-plus-2"));
        icons.add(new Document("exposure-zero"));
        icons.add(new Document("extension"));
        icons.add(new Document("face"));
        icons.add(new Document("fast-forward"));
        icons.add(new Document("fast-rewind"));
        icons.add(new Document("favorite"));
        icons.add(new Document("favorite-border"));
        icons.add(new Document("featured-play-list"));
        icons.add(new Document("featured-video"));
        icons.add(new Document("feedback"));
        icons.add(new Document("fiber-dvr"));
        icons.add(new Document("fiber-manual-record"));
        icons.add(new Document("fiber-new"));
        icons.add(new Document("fiber-pin"));
        icons.add(new Document("fiber-smart-record"));
        icons.add(new Document("file-download"));
        icons.add(new Document("file-upload"));
        icons.add(new Document("filter"));
        icons.add(new Document("filter-1"));
        icons.add(new Document("filter-2"));
        icons.add(new Document("filter-3"));
        icons.add(new Document("filter-4"));
        icons.add(new Document("filter-5"));
        icons.add(new Document("filter-6"));
        icons.add(new Document("filter-7"));
        icons.add(new Document("filter-8"));
        icons.add(new Document("filter-9"));
        icons.add(new Document("filter-9-plus"));
        icons.add(new Document("filter-b-and-w"));
        icons.add(new Document("filter-center-focus"));
        icons.add(new Document("filter-drama"));
        icons.add(new Document("filter-frames"));
        icons.add(new Document("filter-hdr"));
        icons.add(new Document("filter-list"));
        icons.add(new Document("filter-none"));
        icons.add(new Document("filter-tilt-shift"));
        icons.add(new Document("filter-vintage"));
        icons.add(new Document("find-in-page"));
        icons.add(new Document("find-replace"));
        icons.add(new Document("fingerprint"));
        icons.add(new Document("first-page"));
        icons.add(new Document("fitness-center"));
        icons.add(new Document("flag"));
        icons.add(new Document("flare"));
        icons.add(new Document("flash-auto"));
        icons.add(new Document("flash-off"));
        icons.add(new Document("flash-on"));
        icons.add(new Document("flight"));
        icons.add(new Document("flight-land"));
        icons.add(new Document("flight-takeoff"));
        icons.add(new Document("flip"));
        icons.add(new Document("flip-to-back"));
        icons.add(new Document("flip-to-front"));
        icons.add(new Document("folder"));
        icons.add(new Document("folder-open"));
        icons.add(new Document("folder-shared"));
        icons.add(new Document("folder-special"));
        icons.add(new Document("font-download"));
        icons.add(new Document("format-align-center"));
        icons.add(new Document("format-align-justify"));
        icons.add(new Document("format-align-left"));
        icons.add(new Document("format-align-right"));
        icons.add(new Document("format-bold"));
        icons.add(new Document("format-clear"));
        icons.add(new Document("format-color-fill"));
        icons.add(new Document("format-color-reset"));
        icons.add(new Document("format-color-text"));
        icons.add(new Document("format-indent-decrease"));
        icons.add(new Document("format-indent-increase"));
        icons.add(new Document("format-italic"));
        icons.add(new Document("format-line-spacing"));
        icons.add(new Document("format-list-bulleted"));
        icons.add(new Document("format-list-numbered"));
        icons.add(new Document("format-paint"));
        icons.add(new Document("format-quote"));
        icons.add(new Document("format-shapes"));
        icons.add(new Document("format-size"));
        icons.add(new Document("format-strikethrough"));
        icons.add(new Document("format-textdirection-l-to-r"));
        icons.add(new Document("format-textdirection-r-to-l"));
        icons.add(new Document("format-underlined"));
        icons.add(new Document("forum"));
        icons.add(new Document("forward"));
        icons.add(new Document("forward-10"));
        icons.add(new Document("forward-30"));
        icons.add(new Document("forward-5"));
        icons.add(new Document("free-breakfast"));
        icons.add(new Document("fullscreen"));
        icons.add(new Document("fullscreen-exit"));
        icons.add(new Document("functions"));
        icons.add(new Document("g-translate"));
        icons.add(new Document("gamepad"));
        icons.add(new Document("games"));
        icons.add(new Document("gavel"));
        icons.add(new Document("gesture"));
        icons.add(new Document("get-app"));
        icons.add(new Document("gif"));
        icons.add(new Document("golf-course"));
        icons.add(new Document("gps-fixed"));
        icons.add(new Document("gps-not-fixed"));
        icons.add(new Document("gps-off"));
        icons.add(new Document("grade"));
        icons.add(new Document("gradient"));
        icons.add(new Document("grain"));
        icons.add(new Document("graphic-eq"));
        icons.add(new Document("grid-off"));
        icons.add(new Document("grid-on"));
        icons.add(new Document("group"));
        icons.add(new Document("group-add"));
        icons.add(new Document("group-work"));
        icons.add(new Document("hd"));
        icons.add(new Document("hdr-off"));
        icons.add(new Document("hdr-on"));
        icons.add(new Document("hdr-strong"));
        icons.add(new Document("hdr-weak"));
        icons.add(new Document("headset"));
        icons.add(new Document("headset-mic"));
        icons.add(new Document("healing"));
        icons.add(new Document("hearing"));
        icons.add(new Document("help"));
        icons.add(new Document("help-outline"));
        icons.add(new Document("high-quality"));
        icons.add(new Document("highlight"));
        icons.add(new Document("highlight-off"));
        icons.add(new Document("history"));
        icons.add(new Document("home"));
        icons.add(new Document("hot-tub"));
        icons.add(new Document("hotel"));
        icons.add(new Document("hourglass-empty"));
        icons.add(new Document("hourglass-full"));
        icons.add(new Document("http"));
        icons.add(new Document("https"));
        icons.add(new Document("image"));
        icons.add(new Document("image-aspect-ratio"));
        icons.add(new Document("import-contacts"));
        icons.add(new Document("import-export"));
        icons.add(new Document("important-devices"));
        icons.add(new Document("inbox"));
        icons.add(new Document("indeterminate-check-box"));
        icons.add(new Document("info"));
        icons.add(new Document("info-outline"));
        icons.add(new Document("input"));
        icons.add(new Document("insert-chart"));
        icons.add(new Document("insert-comment"));
        icons.add(new Document("insert-drive-file"));
        icons.add(new Document("insert-emoticon"));
        icons.add(new Document("insert-invitation"));
        icons.add(new Document("insert-link"));
        icons.add(new Document("insert-photo"));
        icons.add(new Document("invert-colors"));
        icons.add(new Document("invert-colors-off"));
        icons.add(new Document("iso"));
        icons.add(new Document("keyboard"));
        icons.add(new Document("keyboard-arrow-down"));
        icons.add(new Document("keyboard-arrow-left"));
        icons.add(new Document("keyboard-arrow-right"));
        icons.add(new Document("keyboard-arrow-up"));
        icons.add(new Document("keyboard-backspace"));
        icons.add(new Document("keyboard-capslock"));
        icons.add(new Document("keyboard-hide"));
        icons.add(new Document("keyboard-return"));
        icons.add(new Document("keyboard-tab"));
        icons.add(new Document("keyboard-voice"));
        icons.add(new Document("kitchen"));
        icons.add(new Document("label"));
        icons.add(new Document("label-outline"));
        icons.add(new Document("landscape"));
        icons.add(new Document("language"));
        icons.add(new Document("laptop"));
        icons.add(new Document("laptop-chromebook"));
        icons.add(new Document("laptop-mac"));
        icons.add(new Document("laptop-windows"));
        icons.add(new Document("last-page"));
        icons.add(new Document("launch"));
        icons.add(new Document("layers"));
        icons.add(new Document("layers-clear"));
        icons.add(new Document("leak-add"));
        icons.add(new Document("leak-remove"));
        icons.add(new Document("lens"));
        icons.add(new Document("library-add"));
        icons.add(new Document("library-books"));
        icons.add(new Document("library-music"));
        icons.add(new Document("lightbulb-outline"));
        icons.add(new Document("line-style"));
        icons.add(new Document("line-weight"));
        icons.add(new Document("linear-scale"));
        icons.add(new Document("link"));
        icons.add(new Document("linked-camera"));
        icons.add(new Document("list"));
        icons.add(new Document("live-help"));
        icons.add(new Document("live-tv"));
        icons.add(new Document("local-activity"));
        icons.add(new Document("local-airport"));
        icons.add(new Document("local-atm"));
        icons.add(new Document("local-bar"));
        icons.add(new Document("local-cafe"));
        icons.add(new Document("local-car-wash"));
        icons.add(new Document("local-convenience-store"));
        icons.add(new Document("local-dining"));
        icons.add(new Document("local-drink"));
        icons.add(new Document("local-florist"));
        icons.add(new Document("local-gas-station"));
        icons.add(new Document("local-grocery-store"));
        icons.add(new Document("local-hospital"));
        icons.add(new Document("local-hotel"));
        icons.add(new Document("local-laundry-service"));
        icons.add(new Document("local-library"));
        icons.add(new Document("local-mall"));
        icons.add(new Document("local-movies"));
        icons.add(new Document("local-offer"));
        icons.add(new Document("local-parking"));
        icons.add(new Document("local-pharmacy"));
        icons.add(new Document("local-phone"));
        icons.add(new Document("local-pizza"));
        icons.add(new Document("local-play"));
        icons.add(new Document("local-post-office"));
        icons.add(new Document("local-printshop"));
        icons.add(new Document("local-see"));
        icons.add(new Document("local-shipping"));
        icons.add(new Document("local-taxi"));
        icons.add(new Document("location-city"));
        icons.add(new Document("location-disabled"));
        icons.add(new Document("location-off"));
        icons.add(new Document("location-on"));
        icons.add(new Document("location-searching"));
        icons.add(new Document("lock"));
        icons.add(new Document("lock-open"));
        icons.add(new Document("lock-outline"));
        icons.add(new Document("looks"));
        icons.add(new Document("looks-3"));
        icons.add(new Document("looks-4"));
        icons.add(new Document("looks-5"));
        icons.add(new Document("looks-6"));
        icons.add(new Document("looks-one"));
        icons.add(new Document("looks-two"));
        icons.add(new Document("loop"));
        icons.add(new Document("loupe"));
        icons.add(new Document("low-priority"));
        icons.add(new Document("loyalty"));
        icons.add(new Document("mail"));
        icons.add(new Document("mail-outline"));
        icons.add(new Document("map"));
        icons.add(new Document("markunread"));
        icons.add(new Document("markunread-mailbox"));
        icons.add(new Document("memory"));
        icons.add(new Document("menu"));
        icons.add(new Document("merge-type"));
        icons.add(new Document("message"));
        icons.add(new Document("mic"));
        icons.add(new Document("mic-none"));
        icons.add(new Document("mic-off"));
        icons.add(new Document("mms"));
        icons.add(new Document("mode-comment"));
        icons.add(new Document("mode-edit"));
        icons.add(new Document("monetization-on"));
        icons.add(new Document("money-off"));
        icons.add(new Document("monochrome-photos"));
        icons.add(new Document("mood"));
        icons.add(new Document("mood-bad"));
        icons.add(new Document("more"));
        icons.add(new Document("more-horiz"));
        icons.add(new Document("more-vert"));
        icons.add(new Document("motorcycle"));
        icons.add(new Document("mouse"));
        icons.add(new Document("move-to-inbox"));
        icons.add(new Document("movie"));
        icons.add(new Document("movie-creation"));
        icons.add(new Document("movie-filter"));
        icons.add(new Document("multiline-chart"));
        icons.add(new Document("music-note"));
        icons.add(new Document("music-video"));
        icons.add(new Document("my-location"));
        icons.add(new Document("nature"));
        icons.add(new Document("nature-people"));
        icons.add(new Document("navigate-before"));
        icons.add(new Document("navigate-next"));
        icons.add(new Document("navigation"));
        icons.add(new Document("near-me"));
        icons.add(new Document("network-cell"));
        icons.add(new Document("network-check"));
        icons.add(new Document("network-locked"));
        icons.add(new Document("network-wifi"));
        icons.add(new Document("new-releases"));
        icons.add(new Document("next-week"));
        icons.add(new Document("nfc"));
        icons.add(new Document("no-encryption"));
        icons.add(new Document("no-sim"));
        icons.add(new Document("not-interested"));
        icons.add(new Document("note"));
        icons.add(new Document("note-add"));
        icons.add(new Document("notifications"));
        icons.add(new Document("notifications-active"));
        icons.add(new Document("notifications-none"));
        icons.add(new Document("notifications-off"));
        icons.add(new Document("notifications-paused"));
        icons.add(new Document("offline-pin"));
        icons.add(new Document("ondemand-video"));
        icons.add(new Document("opacity"));
        icons.add(new Document("open-in-browser"));
        icons.add(new Document("open-in-new"));
        icons.add(new Document("open-with"));
        icons.add(new Document("pages"));
        icons.add(new Document("pageview"));
        icons.add(new Document("palette"));
        icons.add(new Document("pan-tool"));
        icons.add(new Document("panorama"));
        icons.add(new Document("panorama-fish-eye"));
        icons.add(new Document("panorama-horizontal"));
        icons.add(new Document("panorama-vertical"));
        icons.add(new Document("panorama-wide-angle"));
        icons.add(new Document("party-mode"));
        icons.add(new Document("pause"));
        icons.add(new Document("pause-circle-filled"));
        icons.add(new Document("pause-circle-outline"));
        icons.add(new Document("payment"));
        icons.add(new Document("people"));
        icons.add(new Document("people-outline"));
        icons.add(new Document("perm-camera-mic"));
        icons.add(new Document("perm-contact-calendar"));
        icons.add(new Document("perm-data-setting"));
        icons.add(new Document("perm-device-information"));
        icons.add(new Document("perm-identity"));
        icons.add(new Document("perm-media"));
        icons.add(new Document("perm-phone-msg"));
        icons.add(new Document("perm-scan-wifi"));
        icons.add(new Document("person"));
        icons.add(new Document("person-add"));
        icons.add(new Document("person-outline"));
        icons.add(new Document("person-pin"));
        icons.add(new Document("person-pin-circle"));
        icons.add(new Document("personal-video"));
        icons.add(new Document("pets"));
        icons.add(new Document("phone"));
        icons.add(new Document("phone-android"));
        icons.add(new Document("phone-bluetooth-speaker"));
        icons.add(new Document("phone-forwarded"));
        icons.add(new Document("phone-in-talk"));
        icons.add(new Document("phone-iphone"));
        icons.add(new Document("phone-locked"));
        icons.add(new Document("phone-missed"));
        icons.add(new Document("phone-paused"));
        icons.add(new Document("phonelink"));
        icons.add(new Document("phonelink-erase"));
        icons.add(new Document("phonelink-lock"));
        icons.add(new Document("phonelink-off"));
        icons.add(new Document("phonelink-ring"));
        icons.add(new Document("phonelink-setup"));
        icons.add(new Document("photo"));
        icons.add(new Document("photo-album"));
        icons.add(new Document("photo-camera"));
        icons.add(new Document("photo-filter"));
        icons.add(new Document("photo-library"));
        icons.add(new Document("photo-size-select-actual"));
        icons.add(new Document("photo-size-select-large"));
        icons.add(new Document("photo-size-select-small"));
        icons.add(new Document("picture-as-pdf"));
        icons.add(new Document("picture-in-picture"));
        icons.add(new Document("picture-in-picture-alt"));
        icons.add(new Document("pie-chart"));
        icons.add(new Document("pie-chart-outlined"));
        icons.add(new Document("pin-drop"));
        icons.add(new Document("place"));
        icons.add(new Document("play-arrow"));
        icons.add(new Document("play-circle-filled"));
        icons.add(new Document("play-circle-outline"));
        icons.add(new Document("play-for-work"));
        icons.add(new Document("playlist-add"));
        icons.add(new Document("playlist-add-check"));
        icons.add(new Document("playlist-play"));
        icons.add(new Document("plus-one"));
        icons.add(new Document("poll"));
        icons.add(new Document("polymer"));
        icons.add(new Document("pool"));
        icons.add(new Document("portable-wifi-off"));
        icons.add(new Document("portrait"));
        icons.add(new Document("power"));
        icons.add(new Document("power-input"));
        icons.add(new Document("power-settings-new"));
        icons.add(new Document("pregnant-woman"));
        icons.add(new Document("present-to-all"));
        icons.add(new Document("print"));
        icons.add(new Document("priority-high"));
        icons.add(new Document("public"));
        icons.add(new Document("publish"));
        icons.add(new Document("query-builder"));
        icons.add(new Document("question-answer"));
        icons.add(new Document("queue"));
        icons.add(new Document("queue-music"));
        icons.add(new Document("queue-play-next"));
        icons.add(new Document("radio"));
        icons.add(new Document("radio-button-checked"));
        icons.add(new Document("radio-button-unchecked"));
        icons.add(new Document("rate-review"));
        icons.add(new Document("receipt"));
        icons.add(new Document("recent-actors"));
        icons.add(new Document("record-voice-over"));
        icons.add(new Document("redeem"));
        icons.add(new Document("redo"));
        icons.add(new Document("refresh"));
        icons.add(new Document("remove"));
        icons.add(new Document("remove-circle"));
        icons.add(new Document("remove-circle-outline"));
        icons.add(new Document("remove-from-queue"));
        icons.add(new Document("remove-red-eye"));
        icons.add(new Document("remove-shopping-cart"));
        icons.add(new Document("reorder"));
        icons.add(new Document("repeat"));
        icons.add(new Document("repeat-one"));
        icons.add(new Document("replay"));
        icons.add(new Document("replay-10"));
        icons.add(new Document("replay-30"));
        icons.add(new Document("replay-5"));
        icons.add(new Document("reply"));
        icons.add(new Document("reply-all"));
        icons.add(new Document("report"));
        icons.add(new Document("report-problem"));
        icons.add(new Document("restaurant"));
        icons.add(new Document("restaurant-menu"));
        icons.add(new Document("restore"));
        icons.add(new Document("restore-page"));
        icons.add(new Document("ring-volume"));
        icons.add(new Document("room"));
        icons.add(new Document("room-service"));
        icons.add(new Document("rotate-90-degrees-ccw"));
        icons.add(new Document("rotate-left"));
        icons.add(new Document("rotate-right"));
        icons.add(new Document("rounded-corner"));
        icons.add(new Document("router"));
        icons.add(new Document("rowing"));
        icons.add(new Document("rss-feed"));
        icons.add(new Document("rv-hookup"));
        icons.add(new Document("satellite"));
        icons.add(new Document("save"));
        icons.add(new Document("scanner"));
        icons.add(new Document("schedule"));
        icons.add(new Document("school"));
        icons.add(new Document("screen-lock-landscape"));
        icons.add(new Document("screen-lock-portrait"));
        icons.add(new Document("screen-lock-rotation"));
        icons.add(new Document("screen-rotation"));
        icons.add(new Document("screen-share"));
        icons.add(new Document("sd-card"));
        icons.add(new Document("sd-storage"));
        icons.add(new Document("search"));
        icons.add(new Document("security"));
        icons.add(new Document("select-all"));
        icons.add(new Document("send"));
        icons.add(new Document("sentiment-dissatisfied"));
        icons.add(new Document("sentiment-neutral"));
        icons.add(new Document("sentiment-satisfied"));
        icons.add(new Document("sentiment-very-dissatisfied"));
        icons.add(new Document("sentiment-very-satisfied"));
        icons.add(new Document("settings"));
        icons.add(new Document("settings-applications"));
        icons.add(new Document("settings-backup-restore"));
        icons.add(new Document("settings-bluetooth"));
        icons.add(new Document("settings-brightness"));
        icons.add(new Document("settings-cell"));
        icons.add(new Document("settings-ethernet"));
        icons.add(new Document("settings-input-antenna"));
        icons.add(new Document("settings-input-component"));
        icons.add(new Document("settings-input-composite"));
        icons.add(new Document("settings-input-hdmi"));
        icons.add(new Document("settings-input-svideo"));
        icons.add(new Document("settings-overscan"));
        icons.add(new Document("settings-phone"));
        icons.add(new Document("settings-power"));
        icons.add(new Document("settings-remote"));
        icons.add(new Document("settings-system-daydream"));
        icons.add(new Document("settings-voice"));
        icons.add(new Document("share"));
        icons.add(new Document("shop"));
        icons.add(new Document("shop-two"));
        icons.add(new Document("shopping-basket"));
        icons.add(new Document("shopping-cart"));
        icons.add(new Document("short-text"));
        icons.add(new Document("show-chart"));
        icons.add(new Document("shuffle"));
        icons.add(new Document("signal-cellular-4-bar"));
        icons.add(new Document("signal-cellular-connected-no-internet-4-bar"));
        icons.add(new Document("signal-cellular-no-sim"));
        icons.add(new Document("signal-cellular-null"));
        icons.add(new Document("signal-cellular-off"));
        icons.add(new Document("signal-wifi-4-bar"));
        icons.add(new Document("signal-wifi-4-bar-lock"));
        icons.add(new Document("signal-wifi-off"));
        icons.add(new Document("sim-card"));
        icons.add(new Document("sim-card-alert"));
        icons.add(new Document("skip-next"));
        icons.add(new Document("skip-previous"));
        icons.add(new Document("slideshow"));
        icons.add(new Document("slow-motion-video"));
        icons.add(new Document("smartphone"));
        icons.add(new Document("smoke-free"));
        icons.add(new Document("smoking-rooms"));
        icons.add(new Document("sms"));
        icons.add(new Document("sms-failed"));
        icons.add(new Document("snooze"));
        icons.add(new Document("sort"));
        icons.add(new Document("sort-by-alpha"));
        icons.add(new Document("spa"));
        icons.add(new Document("space-bar"));
        icons.add(new Document("speaker"));
        icons.add(new Document("speaker-group"));
        icons.add(new Document("speaker-notes"));
        icons.add(new Document("speaker-notes-off"));
        icons.add(new Document("speaker-phone"));
        icons.add(new Document("spellcheck"));
        icons.add(new Document("star"));
        icons.add(new Document("star-border"));
        icons.add(new Document("star-half"));
        icons.add(new Document("stars"));
        icons.add(new Document("stay-current-landscape"));
        icons.add(new Document("stay-current-portrait"));
        icons.add(new Document("stay-primary-landscape"));
        icons.add(new Document("stay-primary-portrait"));
        icons.add(new Document("stop"));
        icons.add(new Document("stop-screen-share"));
        icons.add(new Document("storage"));
        icons.add(new Document("store"));
        icons.add(new Document("store-mall-directory"));
        icons.add(new Document("straighten"));
        icons.add(new Document("streetview"));
        icons.add(new Document("strikethrough-s"));
        icons.add(new Document("style"));
        icons.add(new Document("subdirectory-arrow-left"));
        icons.add(new Document("subdirectory-arrow-right"));
        icons.add(new Document("subject"));
        icons.add(new Document("subscriptions"));
        icons.add(new Document("subtitles"));
        icons.add(new Document("subway"));
        icons.add(new Document("supervisor-account"));
        icons.add(new Document("surround-sound"));
        icons.add(new Document("swap-calls"));
        icons.add(new Document("swap-horiz"));
        icons.add(new Document("swap-vert"));
        icons.add(new Document("swap-vertical-circle"));
        icons.add(new Document("switch-camera"));
        icons.add(new Document("switch-video"));
        icons.add(new Document("sync"));
        icons.add(new Document("sync-disabled"));
        icons.add(new Document("sync-problem"));
        icons.add(new Document("system-update"));
        icons.add(new Document("system-update-alt"));
        icons.add(new Document("tab"));
        icons.add(new Document("tab-unselected"));
        icons.add(new Document("tablet"));
        icons.add(new Document("tablet-android"));
        icons.add(new Document("tablet-mac"));
        icons.add(new Document("tag-faces"));
        icons.add(new Document("tap-and-play"));
        icons.add(new Document("terrain"));
        icons.add(new Document("text-fields"));
        icons.add(new Document("text-format"));
        icons.add(new Document("textsms"));
        icons.add(new Document("texture"));
        icons.add(new Document("theaters"));
        icons.add(new Document("thumb-down"));
        icons.add(new Document("thumb-up"));
        icons.add(new Document("thumbs-up-down"));
        icons.add(new Document("time-to-leave"));
        icons.add(new Document("timelapse"));
        icons.add(new Document("timeline"));
        icons.add(new Document("timer"));
        icons.add(new Document("timer-10"));
        icons.add(new Document("timer-3"));
        icons.add(new Document("timer-off"));
        icons.add(new Document("title"));
        icons.add(new Document("toc"));
        icons.add(new Document("today"));
        icons.add(new Document("toll"));
        icons.add(new Document("tonality"));
        icons.add(new Document("touch-app"));
        icons.add(new Document("toys"));
        icons.add(new Document("track-changes"));
        icons.add(new Document("traffic"));
        icons.add(new Document("train"));
        icons.add(new Document("tram"));
        icons.add(new Document("transfer-within-a-station"));
        icons.add(new Document("transform"));
        icons.add(new Document("translate"));
        icons.add(new Document("trending-down"));
        icons.add(new Document("trending-flat"));
        icons.add(new Document("trending-up"));
        icons.add(new Document("tune"));
        icons.add(new Document("turned-in"));
        icons.add(new Document("turned-in-not"));
        icons.add(new Document("tv"));
        icons.add(new Document("unarchive"));
        icons.add(new Document("undo"));
        icons.add(new Document("unfold-less"));
        icons.add(new Document("unfold-more"));
        icons.add(new Document("update"));
        icons.add(new Document("usb"));
        icons.add(new Document("verified-user"));
        icons.add(new Document("vertical-align-bottom"));
        icons.add(new Document("vertical-align-center"));
        icons.add(new Document("vertical-align-top"));
        icons.add(new Document("vibration"));
        icons.add(new Document("video-call"));
        icons.add(new Document("video-label"));
        icons.add(new Document("video-library"));
        icons.add(new Document("videocam"));
        icons.add(new Document("videocam-off"));
        icons.add(new Document("videogame-asset"));
        icons.add(new Document("view-agenda"));
        icons.add(new Document("view-array"));
        icons.add(new Document("view-carousel"));
        icons.add(new Document("view-column"));
        icons.add(new Document("view-comfy"));
        icons.add(new Document("view-compact"));
        icons.add(new Document("view-day"));
        icons.add(new Document("view-headline"));
        icons.add(new Document("view-list"));
        icons.add(new Document("view-module"));
        icons.add(new Document("view-quilt"));
        icons.add(new Document("view-stream"));
        icons.add(new Document("view-week"));
        icons.add(new Document("vignette"));
        icons.add(new Document("visibility"));
        icons.add(new Document("visibility-off"));
        icons.add(new Document("voice-chat"));
        icons.add(new Document("voicemail"));
        icons.add(new Document("volume-down"));
        icons.add(new Document("volume-mute"));
        icons.add(new Document("volume-off"));
        icons.add(new Document("volume-up"));
        icons.add(new Document("vpn-key"));
        icons.add(new Document("vpn-lock"));
        icons.add(new Document("wallpaper"));
        icons.add(new Document("warning"));
        icons.add(new Document("watch"));
        icons.add(new Document("watch-later"));
        icons.add(new Document("wb-auto"));
        icons.add(new Document("wb-cloudy"));
        icons.add(new Document("wb-incandescent"));
        icons.add(new Document("wb-iridescent"));
        icons.add(new Document("wb-sunny"));
        icons.add(new Document("wc"));
        icons.add(new Document("web"));
        icons.add(new Document("web-asset"));
        icons.add(new Document("weekend"));
        icons.add(new Document("whatshot"));
        icons.add(new Document("widgets"));
        icons.add(new Document("wifi"));
        icons.add(new Document("wifi-lock"));
        icons.add(new Document("wifi-tethering"));
        icons.add(new Document("work"));
        icons.add(new Document("wrap-text"));
        icons.add(new Document("youtube-searched-for"));
        icons.add(new Document("zoom-in"));
        icons.add(new Document("zoom-out"));
        icons.add(new Document("zoom-out-map"));

        faIcons = new ArrayList<>();
        faIcons.add(new Document("fa fa-fw fa-bed", "fa-bed"));
        faIcons.add(new Document("fa fa-fw fa-buysellads", "fa-buysellads"));
        faIcons.add(new Document("fa fa-fw fa-cart-arrow-down", "fa-cart-arrow-down"));
        faIcons.add(new Document("fa fa-fw fa-cart-plus", "fa-cart-plus"));
        faIcons.add(new Document("fa fa-fw fa-connectdevelop", "fa-connectdevelop"));
        faIcons.add(new Document("fa fa-fw fa-dashcube", "fa-dashcube"));
        faIcons.add(new Document("fa fa-fw fa-diamond", "fa-diamond"));
        faIcons.add(new Document("fa fa-fw fa-facebook-official", "fa-facebook-official"));
        faIcons.add(new Document("fa fa-fw fa-forumbee", "fa-forumbee"));
        faIcons.add(new Document("fa fa-fw fa-heartbeat", "fa-heartbeat"));
        faIcons.add(new Document("fa fa-fw fa-hotel", "fa-hotel (alias)"));
        faIcons.add(new Document("fa fa-fw fa-leanpub", "fa-leanpub"));
        faIcons.add(new Document("fa fa-fw fa-mars", "fa-mars"));
        faIcons.add(new Document("fa fa-fw fa-mars-double", "fa-mars-double"));
        faIcons.add(new Document("fa fa-fw fa-mars-stroke", "fa-mars-stroke"));
        faIcons.add(new Document("fa fa-fw fa-mars-stroke-h", "fa-mars-stroke-h"));
        faIcons.add(new Document("fa fa-fw fa-mars-stroke-v", "fa-mars-stroke-v"));
        faIcons.add(new Document("fa fa-fw fa-medium", "fa-medium"));
        faIcons.add(new Document("fa fa-fw fa-mercury", "fa-mercury"));
        faIcons.add(new Document("fa fa-fw fa-motorcycle", "fa-motorcycle"));
        faIcons.add(new Document("fa fa-fw fa-neuter", "fa-neuter"));
        faIcons.add(new Document("fa fa-fw fa-pinterest-p", "fa-pinterest-p"));
        faIcons.add(new Document("fa fa-fw fa-sellsy", "fa-sellsy"));
        faIcons.add(new Document("fa fa-fw fa-server", "fa-server"));
        faIcons.add(new Document("fa fa-fw fa-ship", "fa-ship"));
        faIcons.add(new Document("fa fa-fw fa-shirtsinbulk", "fa-shirtsinbulk"));
        faIcons.add(new Document("fa fa-fw fa-simplybuilt", "fa-simplybuilt"));
        faIcons.add(new Document("fa fa-fw fa-skyatlas", "fa-skyatlas"));
        faIcons.add(new Document("fa fa-fw fa-street-view", "fa-street-view"));
        faIcons.add(new Document("fa fa-fw fa-subway", "fa-subway"));
        faIcons.add(new Document("fa fa-fw fa-train", "fa-train"));
        faIcons.add(new Document("fa fa-fw fa-transgender", "fa-transgender"));
        faIcons.add(new Document("fa fa-fw fa-transgender-alt", "fa-transgender-alt"));
        faIcons.add(new Document("fa fa-fw fa-user-plus", "fa-user-plus"));
        faIcons.add(new Document("fa fa-fw fa-user-secret", "fa-user-secret"));
        faIcons.add(new Document("fa fa-fw fa-user-times", "fa-user-times"));
        faIcons.add(new Document("fa fa-fw fa-venus", "fa-venus"));
        faIcons.add(new Document("fa fa-fw fa-venus-double", "fa-venus-double"));
        faIcons.add(new Document("fa fa-fw fa-venus-mars", "fa-venus-mars"));
        faIcons.add(new Document("fa fa-fw fa-viacoin", "fa-viacoin"));
        faIcons.add(new Document("fa fa-fw fa-whatsapp", "fa-whatsapp"));
        faIcons.add(new Document("fa fa-fw fa-adjust", "fa-adjust"));
        faIcons.add(new Document("fa fa-fw fa-adn", "fa-adn"));
        faIcons.add(new Document("fa fa-fw fa-align-center", "fa-align-center"));
        faIcons.add(new Document("fa fa-fw fa-align-justify", "fa-align-justify"));
        faIcons.add(new Document("fa fa-fw fa-align-left", "fa-align-left"));
        faIcons.add(new Document("fa fa-fw fa-align-right", "fa-align-right"));
        faIcons.add(new Document("fa fa-fw fa-ambulance", "fa-ambulance"));
        faIcons.add(new Document("fa fa-fw fa-anchor", "fa-anchor"));
        faIcons.add(new Document("fa fa-fw fa-android", "fa-android"));
        faIcons.add(new Document("fa fa-fw fa-angellist", "fa-angellist"));
        faIcons.add(new Document("fa fa-fw fa-angle-double-down", "fa-angle-double-down"));
        faIcons.add(new Document("fa fa-fw fa-angle-double-left", "fa-angle-double-left"));
        faIcons.add(new Document("fa fa-fw fa-angle-double-right", "fa-angle-double-right"));
        faIcons.add(new Document("fa fa-fw fa-angle-double-up", "fa-angle-double-up"));
        faIcons.add(new Document("fa fa-fw fa-angle-down", "fa-angle-down"));
        faIcons.add(new Document("fa fa-fw fa-angle-left", "fa-angle-left"));
        faIcons.add(new Document("fa fa-fw fa-angle-right", "fa-angle-right"));
        faIcons.add(new Document("fa fa-fw fa-angle-up", "fa-angle-up"));
        faIcons.add(new Document("fa fa-fw fa-apple", "fa-apple"));
        faIcons.add(new Document("fa fa-fw fa-archive", "fa-archive"));
        faIcons.add(new Document("fa fa-fw fa-area-chart", "fa-area-chart"));
        faIcons.add(new Document("fa fa-fw fa-arrow-circle-down", "fa-arrow-circle-down"));
        faIcons.add(new Document("fa fa-fw fa-arrow-circle-left", "fa-arrow-circle-left"));
        faIcons.add(new Document("fa fa-fw fa-arrow-circle-o-down", "fa-arrow-circle-o-down"));
        faIcons.add(new Document("fa fa-fw fa-arrow-circle-o-left", "fa-arrow-circle-o-left"));
        faIcons.add(new Document("fa fa-fw fa-arrow-circle-o-right", "fa-arrow-circle-o-right"));
        faIcons.add(new Document("fa fa-fw fa-arrow-circle-o-up", "fa-arrow-circle-o-up"));
        faIcons.add(new Document("fa fa-fw fa-arrow-circle-right", "fa-arrow-circle-right"));
        faIcons.add(new Document("fa fa-fw fa-arrow-circle-up", "fa-arrow-circle-up"));
        faIcons.add(new Document("fa fa-fw fa-arrow-down", "fa-arrow-down"));
        faIcons.add(new Document("fa fa-fw fa-arrow-left", "fa-arrow-left"));
        faIcons.add(new Document("fa fa-fw fa-arrow-right", "fa-arrow-right"));
        faIcons.add(new Document("fa fa-fw fa-arrow-up", "fa-arrow-up"));
        faIcons.add(new Document("fa fa-fw fa-arrows", "fa-arrows"));
        faIcons.add(new Document("fa fa-fw fa-arrows-alt", "fa-arrows-alt"));
        faIcons.add(new Document("fa fa-fw fa-arrows-h", "fa-arrows-h"));
        faIcons.add(new Document("fa fa-fw fa-arrows-v", "fa-arrows-v"));
        faIcons.add(new Document("fa fa-fw fa-asterisk", "fa-asterisk"));
        faIcons.add(new Document("fa fa-fw fa-at", "fa-at"));
        faIcons.add(new Document("fa fa-fw fa-automobile", "fa-automobile"));
        faIcons.add(new Document("fa fa-fw fa-backward", "fa-backward"));
        faIcons.add(new Document("fa fa-fw fa-ban", "fa-ban"));
        faIcons.add(new Document("fa fa-fw fa-bank", "fa-bank"));
        faIcons.add(new Document("fa fa-fw fa-bar-chart", "fa-bar-chart"));
        faIcons.add(new Document("fa fa-fw fa-bar-chart-o", "fa-bar-chart-o"));
        faIcons.add(new Document("fa fa-fw fa-barcode", "fa-barcode"));
        faIcons.add(new Document("fa fa-fw fa-bars", "fa-bars"));
        faIcons.add(new Document("fa fa-fw fa-beer", "fa-beer"));
        faIcons.add(new Document("fa fa-fw fa-behance", "fa-behance"));
        faIcons.add(new Document("fa fa-fw fa-behance-square", "fa-behance-square"));
        faIcons.add(new Document("fa fa-fw fa-bell", "fa-bell"));
        faIcons.add(new Document("fa fa-fw fa-bell-o", "fa-bell-o"));
        faIcons.add(new Document("fa fa-fw fa-bell-slash", "fa-bell-slash"));
        faIcons.add(new Document("fa fa-fw fa-bell-slash-o", "fa-bell-slash-o"));
        faIcons.add(new Document("fa fa-fw fa-bicycle", "fa-bicycle"));
        faIcons.add(new Document("fa fa-fw fa-binoculars", "fa-binoculars"));
        faIcons.add(new Document("fa fa-fw fa-birthday-cake", "fa-birthday-cake"));
        faIcons.add(new Document("fa fa-fw fa-bitbucket", "fa-bitbucket"));
        faIcons.add(new Document("fa fa-fw fa-bitbucket-square", "fa-bitbucket-square"));
        faIcons.add(new Document("fa fa-fw fa-bitcoin", "fa-bitcoin"));
        faIcons.add(new Document("fa fa-fw fa-bold", "fa-bold"));
        faIcons.add(new Document("fa fa-fw fa-bolt", "fa-bolt"));
        faIcons.add(new Document("fa fa-fw fa-bomb", "fa-bomb"));
        faIcons.add(new Document("fa fa-fw fa-book", "fa-book"));
        faIcons.add(new Document("fa fa-fw fa-bookmark", "fa-bookmark"));
        faIcons.add(new Document("fa fa-fw fa-bookmark-o", "fa-bookmark-o"));
        faIcons.add(new Document("fa fa-fw fa-briefcase", "fa-briefcase"));
        faIcons.add(new Document("fa fa-fw fa-btc", "fa-btc"));
        faIcons.add(new Document("fa fa-fw fa-bug", "fa-bug"));
        faIcons.add(new Document("fa fa-fw fa-building", "fa-building"));
        faIcons.add(new Document("fa fa-fw fa-building-o", "fa-building-o"));
        faIcons.add(new Document("fa fa-fw fa-bullhorn", "fa-bullhorn"));
        faIcons.add(new Document("fa fa-fw fa-bullseye", "fa-bullseye"));
        faIcons.add(new Document("fa fa-fw fa-bus", "fa-bus"));
        faIcons.add(new Document("fa fa-fw fa-cab", "fa-cab"));
        faIcons.add(new Document("fa fa-fw fa-calculator", "fa-calculator"));
        faIcons.add(new Document("fa fa-fw fa-calendar", "fa-calendar"));
        faIcons.add(new Document("fa fa-fw fa-calendar-o", "fa-calendar-o"));
        faIcons.add(new Document("fa fa-fw fa-camera", "fa-camera"));
        faIcons.add(new Document("fa fa-fw fa-camera-retro", "fa-camera-retro"));
        faIcons.add(new Document("fa fa-fw fa-car", "fa-car"));
        faIcons.add(new Document("fa fa-fw fa-caret-down", "fa-caret-down"));
        faIcons.add(new Document("fa fa-fw fa-caret-left", "fa-caret-left"));
        faIcons.add(new Document("fa fa-fw fa-caret-right", "fa-caret-right"));
        faIcons.add(new Document("fa fa-fw fa-caret-square-o-down", "fa-caret-square-o-down"));
        faIcons.add(new Document("fa fa-fw fa-caret-square-o-left", "fa-caret-square-o-left"));
        faIcons.add(new Document("fa fa-fw fa-caret-square-o-right", "fa-caret-square-o-right"));
        faIcons.add(new Document("fa fa-fw fa-caret-square-o-up", "fa-caret-square-o-up"));
        faIcons.add(new Document("fa fa-fw fa-caret-up", "fa-caret-up"));
        faIcons.add(new Document("fa fa-fw fa-cc", "fa-cc"));
        faIcons.add(new Document("fa fa-fw fa-cc-amex", "fa-cc-amex"));
        faIcons.add(new Document("fa fa-fw fa-cc-discover", "fa-cc-discover"));
        faIcons.add(new Document("fa fa-fw fa-cc-mastercard", "fa-cc-mastercard"));
        faIcons.add(new Document("fa fa-fw fa-cc-paypal", "fa-cc-paypal"));
        faIcons.add(new Document("fa fa-fw fa-cc-stripe", "fa-cc-stripe"));
        faIcons.add(new Document("fa fa-fw fa-cc-visa", "fa-cc-visa"));
        faIcons.add(new Document("fa fa-fw fa-certificate", "fa-certificate"));
        faIcons.add(new Document("fa fa-fw fa-chain", "fa-chain"));
        faIcons.add(new Document("fa fa-fw fa-chain-broken", "fa-chain-broken"));
        faIcons.add(new Document("fa fa-fw fa-check", "fa-check"));
        faIcons.add(new Document("fa fa-fw fa-check-circle", "fa-check-circle"));
        faIcons.add(new Document("fa fa-fw fa-check-circle-o", "fa-check-circle-o"));
        faIcons.add(new Document("fa fa-fw fa-check-square", "fa-check-square"));
        faIcons.add(new Document("fa fa-fw fa-check-square-o", "fa-check-square-o"));
        faIcons.add(new Document("fa fa-fw fa-chevron-circle-down", "fa-chevron-circle-down"));
        faIcons.add(new Document("fa fa-fw fa-chevron-circle-left", "fa-chevron-circle-left"));
        faIcons.add(new Document("fa fa-fw fa-chevron-circle-right", "fa-chevron-circle-right"));
        faIcons.add(new Document("fa fa-fw fa-chevron-circle-up", "fa-chevron-circle-up"));
        faIcons.add(new Document("fa fa-fw fa-chevron-down", "fa-chevron-down"));
        faIcons.add(new Document("fa fa-fw fa-chevron-left", "fa-chevron-left"));
        faIcons.add(new Document("fa fa-fw fa-chevron-right", "fa-chevron-right"));
        faIcons.add(new Document("fa fa-fw fa-chevron-up", "fa-chevron-up"));
        faIcons.add(new Document("fa fa-fw fa-child", "fa-child"));
        faIcons.add(new Document("fa fa-fw fa-circle", "fa-circle"));
        faIcons.add(new Document("fa fa-fw fa-circle-o", "fa-circle-o"));
        faIcons.add(new Document("fa fa-fw fa-circle-o-notch", "fa-circle-o-notch"));
        faIcons.add(new Document("fa fa-fw fa-circle-thin", "fa-circle-thin"));
        faIcons.add(new Document("fa fa-fw fa-clipboard", "fa-clipboard"));
        faIcons.add(new Document("fa fa-fw fa-clock-o", "fa-clock-o"));
        faIcons.add(new Document("fa fa-fw fa-close", "fa-close"));
        faIcons.add(new Document("fa fa-fw fa-cloud", "fa-cloud"));
        faIcons.add(new Document("fa fa-fw fa-cloud-download", "fa-cloud-download"));
        faIcons.add(new Document("fa fa-fw fa-cloud-upload", "fa-cloud-upload"));
        faIcons.add(new Document("fa fa-fw fa-cny", "fa-cny"));
        faIcons.add(new Document("fa fa-fw fa-code", "fa-code"));
        faIcons.add(new Document("fa fa-fw fa-code-fork", "fa-code-fork"));
        faIcons.add(new Document("fa fa-fw fa-codepen", "fa-codepen"));
        faIcons.add(new Document("fa fa-fw fa-coffee", "fa-coffee"));
        faIcons.add(new Document("fa fa-fw fa-cog", "fa-cog"));
        faIcons.add(new Document("fa fa-fw fa-cogs", "fa-cogs"));
        faIcons.add(new Document("fa fa-fw fa-columns", "fa-columns"));
        faIcons.add(new Document("fa fa-fw fa-comment", "fa-comment"));
        faIcons.add(new Document("fa fa-fw fa-comment-o", "fa-comment-o"));
        faIcons.add(new Document("fa fa-fw fa-comments", "fa-comments"));
        faIcons.add(new Document("fa fa-fw fa-comments-o", "fa-comments-o"));
        faIcons.add(new Document("fa fa-fw fa-compass", "fa-compass"));
        faIcons.add(new Document("fa fa-fw fa-compress", "fa-compress"));
        faIcons.add(new Document("fa fa-fw fa-copy", "fa-copy"));
        faIcons.add(new Document("fa fa-fw fa-copyright", "fa-copyright"));
        faIcons.add(new Document("fa fa-fw fa-credit-card", "fa-credit-card"));
        faIcons.add(new Document("fa fa-fw fa-crop", "fa-crop"));
        faIcons.add(new Document("fa fa-fw fa-crosshairs", "fa-crosshairs"));
        faIcons.add(new Document("fa fa-fw fa-css3", "fa-css3"));
        faIcons.add(new Document("fa fa-fw fa-cube", "fa-cube"));
        faIcons.add(new Document("fa fa-fw fa-cubes", "fa-cubes"));
        faIcons.add(new Document("fa fa-fw fa-cut", "fa-cut"));
        faIcons.add(new Document("fa fa-fw fa-cutlery", "fa-cutlery"));
        faIcons.add(new Document("fa fa-fw fa-dashboard", "fa-dashboard"));
        faIcons.add(new Document("fa fa-fw fa-database", "fa-database"));
        faIcons.add(new Document("fa fa-fw fa-dedent", "fa-dedent"));
        faIcons.add(new Document("fa fa-fw fa-delicious", "fa-delicious"));
        faIcons.add(new Document("fa fa-fw fa-desktop", "fa-desktop"));
        faIcons.add(new Document("fa fa-fw fa-deviantart", "fa-deviantart"));
        faIcons.add(new Document("fa fa-fw fa-digg", "fa-digg"));
        faIcons.add(new Document("fa fa-fw fa-dollar", "fa-dollar"));
        faIcons.add(new Document("fa fa-fw fa-dot-circle-o", "fa-dot-circle-o"));
        faIcons.add(new Document("fa fa-fw fa-download", "fa-download"));
        faIcons.add(new Document("fa fa-fw fa-dribbble", "fa-dribbble"));
        faIcons.add(new Document("fa fa-fw fa-dropbox", "fa-dropbox"));
        faIcons.add(new Document("fa fa-fw fa-drupal", "fa-drupal"));
        faIcons.add(new Document("fa fa-fw fa-edit", "fa-edit"));
        faIcons.add(new Document("fa fa-fw fa-eject", "fa-eject"));
        faIcons.add(new Document("fa fa-fw fa-ellipsis-h", "fa-ellipsis-h"));
        faIcons.add(new Document("fa fa-fw fa-ellipsis-v", "fa-ellipsis-v"));
        faIcons.add(new Document("fa fa-fw fa-empire", "fa-empire"));
        faIcons.add(new Document("fa fa-fw fa-envelope", "fa-envelope"));
        faIcons.add(new Document("fa fa-fw fa-envelope-o", "fa-envelope-o"));
        faIcons.add(new Document("fa fa-fw fa-envelope-square", "fa-envelope-square"));
        faIcons.add(new Document("fa fa-fw fa-eraser", "fa-eraser"));
        faIcons.add(new Document("fa fa-fw fa-eur", "fa-eur"));
        faIcons.add(new Document("fa fa-fw fa-euro", "fa-euro"));
        faIcons.add(new Document("fa fa-fw fa-exchange", "fa-exchange"));
        faIcons.add(new Document("fa fa-fw fa-exclamation", "fa-exclamation"));
        faIcons.add(new Document("fa fa-fw fa-exclamation-circle", "fa-exclamation-circle"));
        faIcons.add(new Document("fa fa-fw fa-exclamation-triangle", "fa-exclamation-triangle"));
        faIcons.add(new Document("fa fa-fw fa-expand", "fa-expand"));
        faIcons.add(new Document("fa fa-fw fa-external-link", "fa-external-link"));
        faIcons.add(new Document("fa fa-fw fa-external-link-square", "fa-external-link-square"));
        faIcons.add(new Document("fa fa-fw fa-eye", "fa-eye"));
        faIcons.add(new Document("fa fa-fw fa-eye-slash", "fa-eye-slash"));
        faIcons.add(new Document("fa fa-fw fa-eyedropper", "fa-eyedropper"));
        faIcons.add(new Document("fa fa-fw fa-facebook", "fa-facebook"));
        faIcons.add(new Document("fa fa-fw fa-facebook-square", "fa-facebook-square"));
        faIcons.add(new Document("fa fa-fw fa-fast-backward", "fa-fast-backward"));
        faIcons.add(new Document("fa fa-fw fa-fast-forward", "fa-fast-forward"));
        faIcons.add(new Document("fa fa-fw fa-fax", "fa-fax"));
        faIcons.add(new Document("fa fa-fw fa-female", "fa-female"));
        faIcons.add(new Document("fa fa-fw fa-fighter-jet", "fa-fighter-jet"));
        faIcons.add(new Document("fa fa-fw fa-file", "fa-file"));
        faIcons.add(new Document("fa fa-fw fa-file-archive-o", "fa-file-archive-o"));
        faIcons.add(new Document("fa fa-fw fa-file-audio-o", "fa-file-audio-o"));
        faIcons.add(new Document("fa fa-fw fa-file-code-o", "fa-file-code-o"));
        faIcons.add(new Document("fa fa-fw fa-file-excel-o", "fa-file-excel-o"));
        faIcons.add(new Document("fa fa-fw fa-file-image-o", "fa-file-image-o"));
        faIcons.add(new Document("fa fa-fw fa-file-movie-o", "fa-file-movie-o"));
        faIcons.add(new Document("fa fa-fw fa-file-o", "fa-file-o"));
        faIcons.add(new Document("fa fa-fw fa-file-pdf-o", "fa-file-pdf-o"));
        faIcons.add(new Document("fa fa-fw fa-file-photo-o", "fa-file-photo-o"));
        faIcons.add(new Document("fa fa-fw fa-file-picture-o", "fa-file-picture-o"));
        faIcons.add(new Document("fa fa-fw fa-file-powerpoint-o", "fa-file-powerpoint-o"));
        faIcons.add(new Document("fa fa-fw fa-file-sound-o", "fa-file-sound-o"));
        faIcons.add(new Document("fa fa-fw fa-file-text", "fa-file-text"));
        faIcons.add(new Document("fa fa-fw fa-file-text-o", "fa-file-text-o"));
        faIcons.add(new Document("fa fa-fw fa-file-video-o", "fa-file-video-o"));
        faIcons.add(new Document("fa fa-fw fa-file-word-o", "fa-file-word-o"));
        faIcons.add(new Document("fa fa-fw fa-file-zip-o", "fa-file-zip-o"));
        faIcons.add(new Document("fa fa-fw fa-files-o", "fa-files-o"));
        faIcons.add(new Document("fa fa-fw fa-film", "fa-film"));
        faIcons.add(new Document("fa fa-fw fa-filter", "fa-filter"));
        faIcons.add(new Document("fa fa-fw fa-fire", "fa-fire"));
        faIcons.add(new Document("fa fa-fw fa-fire-extinguisher", "fa-fire-extinguisher"));
        faIcons.add(new Document("fa fa-fw fa-flag", "fa-flag"));
        faIcons.add(new Document("fa fa-fw fa-flag-checkered", "fa-flag-checkered"));
        faIcons.add(new Document("fa fa-fw fa-flag-o", "fa-flag-o"));
        faIcons.add(new Document("fa fa-fw fa-flash", "fa-flash"));
        faIcons.add(new Document("fa fa-fw fa-flask", "fa-flask"));
        faIcons.add(new Document("fa fa-fw fa-flickr", "fa-flickr"));
        faIcons.add(new Document("fa fa-fw fa-floppy-o", "fa-floppy-o"));
        faIcons.add(new Document("fa fa-fw fa-folder", "fa-folder"));
        faIcons.add(new Document("fa fa-fw fa-folder-o", "fa-folder-o"));
        faIcons.add(new Document("fa fa-fw fa-folder-open", "fa-folder-open"));
        faIcons.add(new Document("fa fa-fw fa-folder-open-o", "fa-folder-open-o"));
        faIcons.add(new Document("fa fa-fw fa-font", "fa-font"));
        faIcons.add(new Document("fa fa-fw fa-forward", "fa-forward"));
        faIcons.add(new Document("fa fa-fw fa-foursquare", "fa-foursquare"));
        faIcons.add(new Document("fa fa-fw fa-frown-o", "fa-frown-o"));
        faIcons.add(new Document("fa fa-fw fa-futbol-o", "fa-futbol-o"));
        faIcons.add(new Document("fa fa-fw fa-gamepad", "fa-gamepad"));
        faIcons.add(new Document("fa fa-fw fa-gavel", "fa-gavel"));
        faIcons.add(new Document("fa fa-fw fa-gbp", "fa-gbp"));
        faIcons.add(new Document("fa fa-fw fa-ge", "fa-ge"));
        faIcons.add(new Document("fa fa-fw fa-gear", "fa-gear"));
        faIcons.add(new Document("fa fa-fw fa-gears", "fa-gears"));
        faIcons.add(new Document("fa fa-fw fa-gift", "fa-gift"));
        faIcons.add(new Document("fa fa-fw fa-git", "fa-git"));
        faIcons.add(new Document("fa fa-fw fa-git-square", "fa-git-square"));
        faIcons.add(new Document("fa fa-fw fa-github", "fa-github"));
        faIcons.add(new Document("fa fa-fw fa-github-alt", "fa-github-alt"));
        faIcons.add(new Document("fa fa-fw fa-github-square", "fa-github-square"));
        faIcons.add(new Document("fa fa-fw fa-gittip", "fa-gittip"));
        faIcons.add(new Document("fa fa-fw fa-glass", "fa-glass"));
        faIcons.add(new Document("fa fa-fw fa-globe", "fa-globe"));
        faIcons.add(new Document("fa fa-fw fa-google", "fa-google"));
        faIcons.add(new Document("fa fa-fw fa-google-plus", "fa-google-plus"));
        faIcons.add(new Document("fa fa-fw fa-google-plus-square", "fa-google-plus-square"));
        faIcons.add(new Document("fa fa-fw fa-google-wallet", "fa-google-wallet"));
        faIcons.add(new Document("fa fa-fw fa-graduation-cap", "fa-graduation-cap"));
        faIcons.add(new Document("fa fa-fw fa-group", "fa-group"));
        faIcons.add(new Document("fa fa-fw fa-h-square", "fa-h-square"));
        faIcons.add(new Document("fa fa-fw fa-hacker-news", "fa-hacker-news"));
        faIcons.add(new Document("fa fa-fw fa-hand-o-down", "fa-hand-o-down"));
        faIcons.add(new Document("fa fa-fw fa-hand-o-left", "fa-hand-o-left"));
        faIcons.add(new Document("fa fa-fw fa-hand-o-right", "fa-hand-o-right"));
        faIcons.add(new Document("fa fa-fw fa-hand-o-up", "fa-hand-o-up"));
        faIcons.add(new Document("fa fa-fw fa-hdd-o", "fa-hdd-o"));
        faIcons.add(new Document("fa fa-fw fa-header", "fa-header"));
        faIcons.add(new Document("fa fa-fw fa-headphones", "fa-headphones"));
        faIcons.add(new Document("fa fa-fw fa-heart", "fa-heart"));
        faIcons.add(new Document("fa fa-fw fa-heart-o", "fa-heart-o"));
        faIcons.add(new Document("fa fa-fw fa-history", "fa-history"));
        faIcons.add(new Document("fa fa-fw fa-home", "fa-home"));
        faIcons.add(new Document("fa fa-fw fa-hospital-o", "fa-hospital-o"));
        faIcons.add(new Document("fa fa-fw fa-html5", "fa-html5"));
        faIcons.add(new Document("fa fa-fw fa-ils", "fa-ils"));
        faIcons.add(new Document("fa fa-fw fa-image", "fa-image"));
        faIcons.add(new Document("fa fa-fw fa-inbox", "fa-inbox"));
        faIcons.add(new Document("fa fa-fw fa-indent", "fa-indent"));
        faIcons.add(new Document("fa fa-fw fa-info", "fa-info"));
        faIcons.add(new Document("fa fa-fw fa-info-circle", "fa-info-circle"));
        faIcons.add(new Document("fa fa-fw fa-inr", "fa-inr"));
        faIcons.add(new Document("fa fa-fw fa-instagram", "fa-instagram"));
        faIcons.add(new Document("fa fa-fw fa-institution", "fa-institution"));
        faIcons.add(new Document("fa fa-fw fa-ioxhost", "fa-ioxhost"));
        faIcons.add(new Document("fa fa-fw fa-italic", "fa-italic"));
        faIcons.add(new Document("fa fa-fw fa-joomla", "fa-joomla"));
        faIcons.add(new Document("fa fa-fw fa-jpy", "fa-jpy"));
        faIcons.add(new Document("fa fa-fw fa-jsfiddle", "fa-jsfiddle"));
        faIcons.add(new Document("fa fa-fw fa-key", "fa-key"));
        faIcons.add(new Document("fa fa-fw fa-keyboard-o", "fa-keyboard-o"));
        faIcons.add(new Document("fa fa-fw fa-krw", "fa-krw"));
        faIcons.add(new Document("fa fa-fw fa-language", "fa-language"));
        faIcons.add(new Document("fa fa-fw fa-laptop", "fa-laptop"));
        faIcons.add(new Document("fa fa-fw fa-lastfm", "fa-lastfm"));
        faIcons.add(new Document("fa fa-fw fa-lastfm-square", "fa-lastfm-square"));
        faIcons.add(new Document("fa fa-fw fa-leaf", "fa-leaf"));
        faIcons.add(new Document("fa fa-fw fa-legal", "fa-legal"));
        faIcons.add(new Document("fa fa-fw fa-lemon-o", "fa-lemon-o"));
        faIcons.add(new Document("fa fa-fw fa-level-down", "fa-level-down"));
        faIcons.add(new Document("fa fa-fw fa-level-up", "fa-level-up"));
        faIcons.add(new Document("fa fa-fw fa-life-bouy", "fa-life-bouy"));
        faIcons.add(new Document("fa fa-fw fa-life-buoy", "fa-life-buoy"));
        faIcons.add(new Document("fa fa-fw fa-life-ring", "fa-life-ring"));
        faIcons.add(new Document("fa fa-fw fa-life-saver", "fa-life-saver"));
        faIcons.add(new Document("fa fa-fw fa-lightbulb-o", "fa-lightbulb-o"));
        faIcons.add(new Document("fa fa-fw fa-line-chart", "fa-line-chart"));
        faIcons.add(new Document("fa fa-fw fa-link", "fa-link"));
        faIcons.add(new Document("fa fa-fw fa-linkedin", "fa-linkedin"));
        faIcons.add(new Document("fa fa-fw fa-linkedin-square", "fa-linkedin-square"));
        faIcons.add(new Document("fa fa-fw fa-linux", "fa-linux"));
        faIcons.add(new Document("fa fa-fw fa-list", "fa-list"));
        faIcons.add(new Document("fa fa-fw fa-list-alt", "fa-list-alt"));
        faIcons.add(new Document("fa fa-fw fa-list-ol", "fa-list-ol"));
        faIcons.add(new Document("fa fa-fw fa-list-ul", "fa-list-ul"));
        faIcons.add(new Document("fa fa-fw fa-location-arrow", "fa-location-arrow"));
        faIcons.add(new Document("fa fa-fw fa-lock", "fa-lock"));
        faIcons.add(new Document("fa fa-fw fa-long-arrow-down", "fa-long-arrow-down"));
        faIcons.add(new Document("fa fa-fw fa-long-arrow-left", "fa-long-arrow-left"));
        faIcons.add(new Document("fa fa-fw fa-long-arrow-right", "fa-long-arrow-right"));
        faIcons.add(new Document("fa fa-fw fa-long-arrow-up", "fa-long-arrow-up"));
        faIcons.add(new Document("fa fa-fw fa-magic", "fa-magic"));
        faIcons.add(new Document("fa fa-fw fa-magnet", "fa-magnet"));
        faIcons.add(new Document("fa fa-fw fa-mail-forward", "fa-mail-forward"));
        faIcons.add(new Document("fa fa-fw fa-mail-reply", "fa-mail-reply"));
        faIcons.add(new Document("fa fa-fw fa-mail-reply-all", "fa-mail-reply-all"));
        faIcons.add(new Document("fa fa-fw fa-male", "fa-male"));
        faIcons.add(new Document("fa fa-fw fa-map-marker", "fa-map-marker"));
        faIcons.add(new Document("fa fa-fw fa-maxcdn", "fa-maxcdn"));
        faIcons.add(new Document("fa fa-fw fa-meanpath", "fa-meanpath"));
        faIcons.add(new Document("fa fa-fw fa-medkit", "fa-medkit"));
        faIcons.add(new Document("fa fa-fw fa-meh-o", "fa-meh-o"));
        faIcons.add(new Document("fa fa-fw fa-microphone", "fa-microphone"));
        faIcons.add(new Document("fa fa-fw fa-microphone-slash", "fa-microphone-slash"));
        faIcons.add(new Document("fa fa-fw fa-minus", "fa-minus"));
        faIcons.add(new Document("fa fa-fw fa-minus-circle", "fa-minus-circle"));
        faIcons.add(new Document("fa fa-fw fa-minus-square", "fa-minus-square"));
        faIcons.add(new Document("fa fa-fw fa-minus-square-o", "fa-minus-square-o"));
        faIcons.add(new Document("fa fa-fw fa-mobile", "fa-mobile"));
        faIcons.add(new Document("fa fa-fw fa-mobile-phone", "fa-mobile-phone"));
        faIcons.add(new Document("fa fa-fw fa-money", "fa-money"));
        faIcons.add(new Document("fa fa-fw fa-moon-o", "fa-moon-o"));
        faIcons.add(new Document("fa fa-fw fa-mortar-board", "fa-mortar-board"));
        faIcons.add(new Document("fa fa-fw fa-music", "fa-music"));
        faIcons.add(new Document("fa fa-fw fa-navicon", "fa-navicon"));
        faIcons.add(new Document("fa fa-fw fa-newspaper-o", "fa-newspaper-o"));
        faIcons.add(new Document("fa fa-fw fa-openid", "fa-openid"));
        faIcons.add(new Document("fa fa-fw fa-outdent", "fa-outdent"));
        faIcons.add(new Document("fa fa-fw fa-pagelines", "fa-pagelines"));
        faIcons.add(new Document("fa fa-fw fa-paint-brush", "fa-paint-brush"));
        faIcons.add(new Document("fa fa-fw fa-paper-plane", "fa-paper-plane"));
        faIcons.add(new Document("fa fa-fw fa-paper-plane-o", "fa-paper-plane-o"));
        faIcons.add(new Document("fa fa-fw fa-paperclip", "fa-paperclip"));
        faIcons.add(new Document("fa fa-fw fa-paragraph", "fa-paragraph"));
        faIcons.add(new Document("fa fa-fw fa-paste", "fa-paste"));
        faIcons.add(new Document("fa fa-fw fa-pause", "fa-pause"));
        faIcons.add(new Document("fa fa-fw fa-paw", "fa-paw"));
        faIcons.add(new Document("fa fa-fw fa-paypal", "fa-paypal"));
        faIcons.add(new Document("fa fa-fw fa-pencil", "fa-pencil"));
        faIcons.add(new Document("fa fa-fw fa-pencil-square", "fa-pencil-square"));
        faIcons.add(new Document("fa fa-fw fa-pencil-square-o", "fa-pencil-square-o"));
        faIcons.add(new Document("fa fa-fw fa-phone", "fa-phone"));
        faIcons.add(new Document("fa fa-fw fa-phone-square", "fa-phone-square"));
        faIcons.add(new Document("fa fa-fw fa-photo", "fa-photo"));
        faIcons.add(new Document("fa fa-fw fa-picture-o", "fa-picture-o"));
        faIcons.add(new Document("fa fa-fw fa-pie-chart", "fa-pie-chart"));
        faIcons.add(new Document("fa fa-fw fa-pied-piper", "fa-pied-piper"));
        faIcons.add(new Document("fa fa-fw fa-pied-piper-alt", "fa-pied-piper-alt"));
        faIcons.add(new Document("fa fa-fw fa-pinterest", "fa-pinterest"));
        faIcons.add(new Document("fa fa-fw fa-pinterest-square", "fa-pinterest-square"));
        faIcons.add(new Document("fa fa-fw fa-plane", "fa-plane"));
        faIcons.add(new Document("fa fa-fw fa-play", "fa-play"));
        faIcons.add(new Document("fa fa-fw fa-play-circle", "fa-play-circle"));
        faIcons.add(new Document("fa fa-fw fa-play-circle-o", "fa-play-circle-o"));
        faIcons.add(new Document("fa fa-fw fa-plug", "fa-plug"));
        faIcons.add(new Document("fa fa-fw fa-plus", "fa-plus"));
        faIcons.add(new Document("fa fa-fw fa-plus-circle", "fa-plus-circle"));
        faIcons.add(new Document("fa fa-fw fa-plus-square", "fa-plus-square"));
        faIcons.add(new Document("fa fa-fw fa-plus-square-o", "fa-plus-square-o"));
        faIcons.add(new Document("fa fa-fw fa-power-off", "fa-power-off"));
        faIcons.add(new Document("fa fa-fw fa-print", "fa-print"));
        faIcons.add(new Document("fa fa-fw fa-puzzle-piece", "fa-puzzle-piece"));
        faIcons.add(new Document("fa fa-fw fa-qq", "fa-qq"));
        faIcons.add(new Document("fa fa-fw fa-qrcode", "fa-qrcode"));
        faIcons.add(new Document("fa fa-fw fa-question", "fa-question"));
        faIcons.add(new Document("fa fa-fw fa-question-circle", "fa-question-circle"));
        faIcons.add(new Document("fa fa-fw fa-quote-left", "fa-quote-left"));
        faIcons.add(new Document("fa fa-fw fa-quote-right", "fa-quote-right"));
        faIcons.add(new Document("fa fa-fw fa-ra", "fa-ra"));
        faIcons.add(new Document("fa fa-fw fa-random", "fa-random"));
        faIcons.add(new Document("fa fa-fw fa-rebel", "fa-rebel"));
        faIcons.add(new Document("fa fa-fw fa-recycle", "fa-recycle"));
        faIcons.add(new Document("fa fa-fw fa-reddit", "fa-reddit"));
        faIcons.add(new Document("fa fa-fw fa-reddit-square", "fa-reddit-square"));
        faIcons.add(new Document("fa fa-fw fa-refresh", "fa-refresh"));
        faIcons.add(new Document("fa fa-fw fa-remove", "fa-remove"));
        faIcons.add(new Document("fa fa-fw fa-renren", "fa-renren"));
        faIcons.add(new Document("fa fa-fw fa-reorder", "fa-reorder"));
        faIcons.add(new Document("fa fa-fw fa-repeat", "fa-repeat"));
        faIcons.add(new Document("fa fa-fw fa-reply", "fa-reply"));
        faIcons.add(new Document("fa fa-fw fa-reply-all", "fa-reply-all"));
        faIcons.add(new Document("fa fa-fw fa-retweet", "fa-retweet"));
        faIcons.add(new Document("fa fa-fw fa-rmb", "fa-rmb"));
        faIcons.add(new Document("fa fa-fw fa-road", "fa-road"));
        faIcons.add(new Document("fa fa-fw fa-rocket", "fa-rocket"));
        faIcons.add(new Document("fa fa-fw fa-rotate-left", "fa-rotate-left"));
        faIcons.add(new Document("fa fa-fw fa-rotate-right", "fa-rotate-right"));
        faIcons.add(new Document("fa fa-fw fa-rouble", "fa-rouble"));
        faIcons.add(new Document("fa fa-fw fa-rss", "fa-rss"));
        faIcons.add(new Document("fa fa-fw fa-rss-square", "fa-rss-square"));
        faIcons.add(new Document("fa fa-fw fa-rub", "fa-rub"));
        faIcons.add(new Document("fa fa-fw fa-ruble", "fa-ruble"));
        faIcons.add(new Document("fa fa-fw fa-rupee", "fa-rupee"));
        faIcons.add(new Document("fa fa-fw fa-save", "fa-save"));
        faIcons.add(new Document("fa fa-fw fa-scissors", "fa-scissors"));
        faIcons.add(new Document("fa fa-fw fa-search", "fa-search"));
        faIcons.add(new Document("fa fa-fw fa-search-minus", "fa-search-minus"));
        faIcons.add(new Document("fa fa-fw fa-search-plus", "fa-search-plus"));
        faIcons.add(new Document("fa fa-fw fa-send", "fa-send"));
        faIcons.add(new Document("fa fa-fw fa-send-o", "fa-send-o"));
        faIcons.add(new Document("fa fa-fw fa-share", "fa-share"));
        faIcons.add(new Document("fa fa-fw fa-share-alt", "fa-share-alt"));
        faIcons.add(new Document("fa fa-fw fa-share-alt-square", "fa-share-alt-square"));
        faIcons.add(new Document("fa fa-fw fa-share-square", "fa-share-square"));
        faIcons.add(new Document("fa fa-fw fa-share-square-o", "fa-share-square-o"));
        faIcons.add(new Document("fa fa-fw fa-shekel", "fa-shekel"));
        faIcons.add(new Document("fa fa-fw fa-sheqel", "fa-sheqel"));
        faIcons.add(new Document("fa fa-fw fa-shield", "fa-shield"));
        faIcons.add(new Document("fa fa-fw fa-shopping-cart", "fa-shopping-cart"));
        faIcons.add(new Document("fa fa-fw fa-sign-in", "fa-sign-in"));
        faIcons.add(new Document("fa fa-fw fa-sign-out", "fa-sign-out"));
        faIcons.add(new Document("fa fa-fw fa-signal", "fa-signal"));
        faIcons.add(new Document("fa fa-fw fa-sitemap", "fa-sitemap"));
        faIcons.add(new Document("fa fa-fw fa-skype", "fa-skype"));
        faIcons.add(new Document("fa fa-fw fa-slack", "fa-slack"));
        faIcons.add(new Document("fa fa-fw fa-sliders", "fa-sliders"));
        faIcons.add(new Document("fa fa-fw fa-slideshare", "fa-slideshare"));
        faIcons.add(new Document("fa fa-fw fa-smile-o", "fa-smile-o"));
        faIcons.add(new Document("fa fa-fw fa-soccer-ball-o", "fa-soccer-ball-o"));
        faIcons.add(new Document("fa fa-fw fa-sort", "fa-sort"));
        faIcons.add(new Document("fa fa-fw fa-sort-alpha-asc", "fa-sort-alpha-asc"));
        faIcons.add(new Document("fa fa-fw fa-sort-alpha-desc", "fa-sort-alpha-desc"));
        faIcons.add(new Document("fa fa-fw fa-sort-amount-asc", "fa-sort-amount-asc"));
        faIcons.add(new Document("fa fa-fw fa-sort-amount-desc", "fa-sort-amount-desc"));
        faIcons.add(new Document("fa fa-fw fa-sort-asc", "fa-sort-asc"));
        faIcons.add(new Document("fa fa-fw fa-sort-desc", "fa-sort-desc"));
        faIcons.add(new Document("fa fa-fw fa-sort-down", "fa-sort-down"));
        faIcons.add(new Document("fa fa-fw fa-sort-numeric-asc", "fa-sort-numeric-asc"));
        faIcons.add(new Document("fa fa-fw fa-sort-numeric-desc", "fa-sort-numeric-desc"));
        faIcons.add(new Document("fa fa-fw fa-sort-up", "fa-sort-up"));
        faIcons.add(new Document("fa fa-fw fa-soundcloud", "fa-soundcloud"));
        faIcons.add(new Document("fa fa-fw fa-space-shuttle", "fa-space-shuttle"));
        faIcons.add(new Document("fa fa-fw fa-spinner", "fa-spinner"));
        faIcons.add(new Document("fa fa-fw fa-spoon", "fa-spoon"));
        faIcons.add(new Document("fa fa-fw fa-spotify", "fa-spotify"));
        faIcons.add(new Document("fa fa-fw fa-square", "fa-square"));
        faIcons.add(new Document("fa fa-fw fa-square-o", "fa-square-o"));
        faIcons.add(new Document("fa fa-fw fa-stack-exchange", "fa-stack-exchange"));
        faIcons.add(new Document("fa fa-fw fa-stack-overflow", "fa-stack-overflow"));
        faIcons.add(new Document("fa fa-fw fa-star", "fa-star"));
        faIcons.add(new Document("fa fa-fw fa-star-half", "fa-star-half"));
        faIcons.add(new Document("fa fa-fw fa-star-half-empty", "fa-star-half-empty"));
        faIcons.add(new Document("fa fa-fw fa-star-half-full", "fa-star-half-full"));
        faIcons.add(new Document("fa fa-fw fa-star-half-o", "fa-star-half-o"));
        faIcons.add(new Document("fa fa-fw fa-star-o", "fa-star-o"));
        faIcons.add(new Document("fa fa-fw fa-steam", "fa-steam"));
        faIcons.add(new Document("fa fa-fw fa-steam-square", "fa-steam-square"));
        faIcons.add(new Document("fa fa-fw fa-step-backward", "fa-step-backward"));
        faIcons.add(new Document("fa fa-fw fa-step-forward", "fa-step-forward"));
        faIcons.add(new Document("fa fa-fw fa-stethoscope", "fa-stethoscope"));
        faIcons.add(new Document("fa fa-fw fa-stop", "fa-stop"));
        faIcons.add(new Document("fa fa-fw fa-strikethrough", "fa-strikethrough"));
        faIcons.add(new Document("fa fa-fw fa-stumbleupon", "fa-stumbleupon"));
        faIcons.add(new Document("fa fa-fw fa-stumbleupon-circle", "fa-stumbleupon-circle"));
        faIcons.add(new Document("fa fa-fw fa-subscript", "fa-subscript"));
        faIcons.add(new Document("fa fa-fw fa-suitcase", "fa-suitcase"));
        faIcons.add(new Document("fa fa-fw fa-sun-o", "fa-sun-o"));
        faIcons.add(new Document("fa fa-fw fa-superscript", "fa-superscript"));
        faIcons.add(new Document("fa fa-fw fa-support", "fa-support"));
        faIcons.add(new Document("fa fa-fw fa-table", "fa-table"));
        faIcons.add(new Document("fa fa-fw fa-tablet", "fa-tablet"));
        faIcons.add(new Document("fa fa-fw fa-tachometer", "fa-tachometer"));
        faIcons.add(new Document("fa fa-fw fa-tag", "fa-tag"));
        faIcons.add(new Document("fa fa-fw fa-tags", "fa-tags"));
        faIcons.add(new Document("fa fa-fw fa-tasks", "fa-tasks"));
        faIcons.add(new Document("fa fa-fw fa-taxi", "fa-taxi"));
        faIcons.add(new Document("fa fa-fw fa-tencent-weibo", "fa-tencent-weibo"));
        faIcons.add(new Document("fa fa-fw fa-terminal", "fa-terminal"));
        faIcons.add(new Document("fa fa-fw fa-text-height", "fa-text-height"));
        faIcons.add(new Document("fa fa-fw fa-text-width", "fa-text-width"));
        faIcons.add(new Document("fa fa-fw fa-th", "fa-th"));
        faIcons.add(new Document("fa fa-fw fa-th-large", "fa-th-large"));
        faIcons.add(new Document("fa fa-fw fa-th-list", "fa-th-list"));
        faIcons.add(new Document("fa fa-fw fa-thumb-tack", "fa-thumb-tack"));
        faIcons.add(new Document("fa fa-fw fa-thumbs-down", "fa-thumbs-down"));
        faIcons.add(new Document("fa fa-fw fa-thumbs-o-down", "fa-thumbs-o-down"));
        faIcons.add(new Document("fa fa-fw fa-thumbs-o-up", "fa-thumbs-o-up"));
        faIcons.add(new Document("fa fa-fw fa-thumbs-up", "fa-thumbs-up"));
        faIcons.add(new Document("fa fa-fw fa-ticket", "fa-ticket"));
        faIcons.add(new Document("fa fa-fw fa-times", "fa-times"));
        faIcons.add(new Document("fa fa-fw fa-times-circle", "fa-times-circle"));
        faIcons.add(new Document("fa fa-fw fa-times-circle-o", "fa-times-circle-o"));
        faIcons.add(new Document("fa fa-fw fa-tint", "fa-tint"));
        faIcons.add(new Document("fa fa-fw fa-toggle-down", "fa-toggle-down"));
        faIcons.add(new Document("fa fa-fw fa-toggle-left", "fa-toggle-left"));
        faIcons.add(new Document("fa fa-fw fa-toggle-off", "fa-toggle-off"));
        faIcons.add(new Document("fa fa-fw fa-toggle-on", "fa-toggle-on"));
        faIcons.add(new Document("fa fa-fw fa-toggle-right", "fa-toggle-right"));
        faIcons.add(new Document("fa fa-fw fa-toggle-up", "fa-toggle-up"));
        faIcons.add(new Document("fa fa-fw fa-trash", "fa-trash"));
        faIcons.add(new Document("fa fa-fw fa-trash-o", "fa-trash-o"));
        faIcons.add(new Document("fa fa-fw fa-tree", "fa-tree"));
        faIcons.add(new Document("fa fa-fw fa-trello", "fa-trello"));
        faIcons.add(new Document("fa fa-fw fa-trophy", "fa-trophy"));
        faIcons.add(new Document("fa fa-fw fa-truck", "fa-truck"));
        faIcons.add(new Document("fa fa-fw fa-try", "fa-try"));
        faIcons.add(new Document("fa fa-fw fa-tty", "fa-tty"));
        faIcons.add(new Document("fa fa-fw fa-tumblr", "fa-tumblr"));
        faIcons.add(new Document("fa fa-fw fa-tumblr-square", "fa-tumblr-square"));
        faIcons.add(new Document("fa fa-fw fa-turkish-lira", "fa-turkish-lira"));
        faIcons.add(new Document("fa fa-fw fa-twitch", "fa-twitch"));
        faIcons.add(new Document("fa fa-fw fa-twitter", "fa-twitter"));
        faIcons.add(new Document("fa fa-fw fa-twitter-square", "fa-twitter-square"));
        faIcons.add(new Document("fa fa-fw fa-umbrella", "fa-umbrella"));
        faIcons.add(new Document("fa fa-fw fa-underline", "fa-underline"));
        faIcons.add(new Document("fa fa-fw fa-undo", "fa-undo"));
        faIcons.add(new Document("fa fa-fw fa-university", "fa-university"));
        faIcons.add(new Document("fa fa-fw fa-unlink", "fa-unlink"));
        faIcons.add(new Document("fa fa-fw fa-unlock", "fa-unlock"));
        faIcons.add(new Document("fa fa-fw fa-unlock-alt", "fa-unlock-alt"));
        faIcons.add(new Document("fa fa-fw fa-unsorted", "fa-unsorted"));
        faIcons.add(new Document("fa fa-fw fa-upload", "fa-upload"));
        faIcons.add(new Document("fa fa-fw fa-usd", "fa-usd"));
        faIcons.add(new Document("fa fa-fw fa-user", "fa-user"));
        faIcons.add(new Document("fa fa-fw fa-user-md", "fa-user-md"));
        faIcons.add(new Document("fa fa-fw fa-users", "fa-users"));
        faIcons.add(new Document("fa fa-fw fa-video-camera", "fa-video-camera"));
        faIcons.add(new Document("fa fa-fw fa-vimeo-square", "fa-vimeo-square"));
        faIcons.add(new Document("fa fa-fw fa-vine", "fa-vine"));
        faIcons.add(new Document("fa fa-fw fa-vk", "fa-vk"));
        faIcons.add(new Document("fa fa-fw fa-volume-down", "fa-volume-down"));
        faIcons.add(new Document("fa fa-fw fa-volume-off", "fa-volume-off"));
        faIcons.add(new Document("fa fa-fw fa-volume-up", "fa-volume-up"));
        faIcons.add(new Document("fa fa-fw fa-warning", "fa-warning"));
        faIcons.add(new Document("fa fa-fw fa-wechat", "fa-wechat"));
        faIcons.add(new Document("fa fa-fw fa-weibo", "fa-weibo"));
        faIcons.add(new Document("fa fa-fw fa-weixin", "fa-weixin"));
        faIcons.add(new Document("fa fa-fw fa-wheelchair", "fa-wheelchair"));
        faIcons.add(new Document("fa fa-fw fa-wifi", "fa-wifi"));
        faIcons.add(new Document("fa fa-fw fa-windows", "fa-windows"));
        faIcons.add(new Document("fa fa-fw fa-won", "fa-won"));
        faIcons.add(new Document("fa fa-fw fa-wordpress", "fa-wordpress"));
        faIcons.add(new Document("fa fa-fw fa-wrench", "fa-wrench"));
        faIcons.add(new Document("fa fa-fw fa-xing", "fa-xing"));
        faIcons.add(new Document("fa fa-fw fa-xing-square", "fa-xing-square"));
        faIcons.add(new Document("fa fa-fw fa-yahoo", "fa-yahoo"));
        faIcons.add(new Document("fa fa-fw fa-yelp", "fa-yelp"));
        faIcons.add(new Document("fa fa-fw fa-yen", "fa-yen"));
        faIcons.add(new Document("fa fa-fw fa-youtube", "fa-youtube"));
        faIcons.add(new Document("fa fa-fw fa-youtube-play", "fa-youtube-play"));
        faIcons.add(new Document("fa fa-fw fa-youtube-square", "fa-youtube-square"));

    }

    public List<Document> getIcons() {
        return icons;
    }

    public void setIcons(List<Document> icons) {
        this.icons = icons;
    }

    public List<Document> getFaIcons() {
        return faIcons;
    }

    public void setFaIcons(List<Document> faIcons) {
        this.faIcons = faIcons;
    }

}
