
package ec.com.trafficcontrol;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MetodosPort", targetNamespace = "http://trafficcontrol.com.ec")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MetodosPort {


    /**
     * 
     * @param usuario
     * @param contrasenia
     * @param placa
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "consultaDeudas", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaDeudas")
    @ResponseWrapper(localName = "consultaDeudasResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaDeudasResponse")
    public String consultaDeudas(
        @WebParam(name = "placa", targetNamespace = "")
        String placa,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param fecha
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "obtieneCatalogoSeguridad", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneCatalogoSeguridad")
    @ResponseWrapper(localName = "obtieneCatalogoSeguridadResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneCatalogoSeguridadResponse")
    public String obtieneCatalogoSeguridad(
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param fecha
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "obtieneTarifarioServicio", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneTarifarioServicio")
    @ResponseWrapper(localName = "obtieneTarifarioServicioResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneTarifarioServicioResponse")
    public String obtieneTarifarioServicio(
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param placa
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "consultaVehiculoxplaca", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaVehiculoxplaca")
    @ResponseWrapper(localName = "consultaVehiculoxplacaResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaVehiculoxplacaResponse")
    public String consultaVehiculoxplaca(
        @WebParam(name = "placa", targetNamespace = "")
        String placa);

    /**
     * 
     * @param fecha
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "obtieneCatalogoParqueo", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneCatalogoParqueo")
    @ResponseWrapper(localName = "obtieneCatalogoParqueoResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneCatalogoParqueoResponse")
    public String obtieneCatalogoParqueo(
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param identificacion
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "consultaDatosLicencia", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaDatosLicencia")
    @ResponseWrapper(localName = "consultaDatosLicenciaResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaDatosLicenciaResponse")
    public String consultaDatosLicencia(
        @WebParam(name = "identificacion", targetNamespace = "")
        String identificacion,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param serial
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "validaEquipomovil", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ValidaEquipomovil")
    @ResponseWrapper(localName = "validaEquipomovilResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ValidaEquipomovilResponse")
    public String validaEquipomovil(
        @WebParam(name = "serial", targetNamespace = "")
        String serial);

    /**
     * 
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "consultaSalarioBasicoUnificado", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaSalarioBasicoUnificado")
    @ResponseWrapper(localName = "consultaSalarioBasicoUnificadoResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaSalarioBasicoUnificadoResponse")
    public String consultaSalarioBasicoUnificado(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "obtieneCatalogoservicios", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneCatalogoservicios")
    @ResponseWrapper(localName = "obtieneCatalogoserviciosResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneCatalogoserviciosResponse")
    public String obtieneCatalogoservicios();

    /**
     * 
     * @param placa
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "identificaVehiculoPlaca", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.IdentificaVehiculoPlaca")
    @ResponseWrapper(localName = "identificaVehiculoPlacaResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.IdentificaVehiculoPlacaResponse")
    public String identificaVehiculoPlaca(
        @WebParam(name = "placa", targetNamespace = "")
        String placa);

    /**
     * 
     * @param placa
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "consultaVehiculoSRI", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaVehiculoSRI")
    @ResponseWrapper(localName = "consultaVehiculoSRIResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaVehiculoSRIResponse")
    public String consultaVehiculoSRI(
        @WebParam(name = "placa", targetNamespace = "")
        String placa);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "obtieneCentrorevision", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneCentrorevision")
    @ResponseWrapper(localName = "obtieneCentrorevisionResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneCentrorevisionResponse")
    public String obtieneCentrorevision();

    /**
     * 
     * @param numeroidentificacion
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "consultaPersonaRegistrocivil", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaPersonaRegistrocivil")
    @ResponseWrapper(localName = "consultaPersonaRegistrocivilResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaPersonaRegistrocivilResponse")
    public String consultaPersonaRegistrocivil(
        @WebParam(name = "numeroidentificacion", targetNamespace = "")
        String numeroidentificacion,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param codigo
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "consultaTituloHabilitante", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaTituloHabilitante")
    @ResponseWrapper(localName = "consultaTituloHabilitanteResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaTituloHabilitanteResponse")
    public String consultaTituloHabilitante(
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param cedula
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "consultaDiscapacidad", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaDiscapacidad")
    @ResponseWrapper(localName = "consultaDiscapacidadResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ConsultaDiscapacidadResponse")
    public String consultaDiscapacidad(
        @WebParam(name = "cedula", targetNamespace = "")
        String cedula,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param fecha
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "obtieneCatalogoLocalidad", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneCatalogoLocalidad")
    @ResponseWrapper(localName = "obtieneCatalogoLocalidadResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneCatalogoLocalidadResponse")
    public String obtieneCatalogoLocalidad(
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param fecha
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "obtieneEquipoMovilApp", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneEquipoMovilApp")
    @ResponseWrapper(localName = "obtieneEquipoMovilAppResponse", targetNamespace = "http://trafficcontrol.com.ec", className = "ec.com.trafficcontrol.ObtieneEquipoMovilAppResponse")
    public String obtieneEquipoMovilApp(
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

}
