
package ec.com.portaltramite.tc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MetodosPort", targetNamespace = "http://tc.portaltramite.com.ec")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MetodosPort {


    /**
     * 
     * @param tipoidentificacion
     * @param numeroidentificacion
     * @param usuario
     * @param contrasenia
     * @param tipoconsulta
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "consultaPersona", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ConsultaPersona")
    @ResponseWrapper(localName = "consultaPersonaResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ConsultaPersonaResponse")
    public String consultaPersona(
        @WebParam(name = "tipoidentificacion", targetNamespace = "")
        String tipoidentificacion,
        @WebParam(name = "numeroidentificacion", targetNamespace = "")
        String numeroidentificacion,
        @WebParam(name = "tipoconsulta", targetNamespace = "")
        String tipoconsulta,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param datos
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "sincronizaRolSistema", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.SincronizaRolSistema")
    @ResponseWrapper(localName = "sincronizaRolSistemaResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.SincronizaRolSistemaResponse")
    public String sincronizaRolSistema(
        @WebParam(name = "datos", targetNamespace = "")
        String datos,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param idsolicitud
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "actualizaSolicitudXCaducidad", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ActualizaSolicitudXCaducidad")
    @ResponseWrapper(localName = "actualizaSolicitudXCaducidadResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ActualizaSolicitudXCaducidadResponse")
    public String actualizaSolicitudXCaducidad(
        @WebParam(name = "idsolicitud", targetNamespace = "")
        long idsolicitud,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "desactivaUsuario", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.DesactivaUsuario")
    @ResponseWrapper(localName = "desactivaUsuarioResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.DesactivaUsuarioResponse")
    public String desactivaUsuario(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario);

    /**
     * 
     * @param idcentrorevision
     * @param fecha
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "obtieneHorarioTurno", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ObtieneHorarioTurno")
    @ResponseWrapper(localName = "obtieneHorarioTurnoResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ObtieneHorarioTurnoResponse")
    public String obtieneHorarioTurno(
        @WebParam(name = "idcentrorevision", targetNamespace = "")
        long idcentrorevision,
        @WebParam(name = "fecha", targetNamespace = "")
        String fecha,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param datos
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "registraUsuario", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.RegistraUsuario")
    @ResponseWrapper(localName = "registraUsuarioResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.RegistraUsuarioResponse")
    public String registraUsuario(
        @WebParam(name = "datos", targetNamespace = "")
        String datos,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param idsolicitud
     * @param usuario
     * @param contrasenia
     * @param turno
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "confirmaReservaturno", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ConfirmaReservaturno")
    @ResponseWrapper(localName = "confirmaReservaturnoResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ConfirmaReservaturnoResponse")
    public String confirmaReservaturno(
        @WebParam(name = "idsolicitud", targetNamespace = "")
        long idsolicitud,
        @WebParam(name = "turno", targetNamespace = "")
        long turno,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param identificacion
     * @param usuario
     * @param contrasenia
     * @param codigoservicio
     * @param placa
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "generaOrdenpagomatriculacion", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.GeneraOrdenpagomatriculacion")
    @ResponseWrapper(localName = "generaOrdenpagomatriculacionResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.GeneraOrdenpagomatriculacionResponse")
    public String generaOrdenpagomatriculacion(
        @WebParam(name = "identificacion", targetNamespace = "")
        String identificacion,
        @WebParam(name = "placa", targetNamespace = "")
        String placa,
        @WebParam(name = "codigoservicio", targetNamespace = "")
        String codigoservicio,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param codigosolicitud
     * @param usuario
     * @param contrasenia
     * @param codigoservicio
     * @param tipoconsulta
     * @param comentario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "finalizaSolicitudXReferencia", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.FinalizaSolicitudXReferencia")
    @ResponseWrapper(localName = "finalizaSolicitudXReferenciaResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.FinalizaSolicitudXReferenciaResponse")
    public String finalizaSolicitudXReferencia(
        @WebParam(name = "codigoservicio", targetNamespace = "")
        String codigoservicio,
        @WebParam(name = "tipoconsulta", targetNamespace = "")
        String tipoconsulta,
        @WebParam(name = "codigosolicitud", targetNamespace = "")
        String codigosolicitud,
        @WebParam(name = "comentario", targetNamespace = "")
        String comentario,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param datospersona
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "registraPersona", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.RegistraPersona")
    @ResponseWrapper(localName = "registraPersonaResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.RegistraPersonaResponse")
    public String registraPersona(
        @WebParam(name = "datospersona", targetNamespace = "")
        String datospersona,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param identificacion
     * @param usuario
     * @param contrasenia
     * @param codigoservicio
     * @param placa
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "consultaVehiculo", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ConsultaVehiculo")
    @ResponseWrapper(localName = "consultaVehiculoResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ConsultaVehiculoResponse")
    public String consultaVehiculo(
        @WebParam(name = "identificacion", targetNamespace = "")
        String identificacion,
        @WebParam(name = "placa", targetNamespace = "")
        String placa,
        @WebParam(name = "codigoservicio", targetNamespace = "")
        String codigoservicio,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param valor
     * @param usuario
     * @param contrasenia
     * @param tipoconsulta
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "obtieneOrdenPagoPdf", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ObtieneOrdenPagoPdf")
    @ResponseWrapper(localName = "obtieneOrdenPagoPdfResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ObtieneOrdenPagoPdfResponse")
    public byte[] obtieneOrdenPagoPdf(
        @WebParam(name = "tipoconsulta", targetNamespace = "")
        String tipoconsulta,
        @WebParam(name = "valor", targetNamespace = "")
        String valor,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param idsolicitud
     * @param usuario
     * @param contrasenia
     * @param comentario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "anulaSolicitud", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.AnulaSolicitud")
    @ResponseWrapper(localName = "anulaSolicitudResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.AnulaSolicitudResponse")
    public String anulaSolicitud(
        @WebParam(name = "idsolicitud", targetNamespace = "")
        long idsolicitud,
        @WebParam(name = "comentario", targetNamespace = "")
        String comentario,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param identificacion
     * @param usuario
     * @param contrasenia
     * @param placa
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "consultaListadotramite", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ConsultaListadotramite")
    @ResponseWrapper(localName = "consultaListadotramiteResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ConsultaListadotramiteResponse")
    public String consultaListadotramite(
        @WebParam(name = "identificacion", targetNamespace = "")
        String identificacion,
        @WebParam(name = "placa", targetNamespace = "")
        String placa,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param centrorevision
     * @param urlturno
     * @param idsolicitud
     * @param usuario
     * @param contrasenia
     * @param turno
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "generaReservaturno", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.GeneraReservaturno")
    @ResponseWrapper(localName = "generaReservaturnoResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.GeneraReservaturnoResponse")
    public String generaReservaturno(
        @WebParam(name = "idsolicitud", targetNamespace = "")
        long idsolicitud,
        @WebParam(name = "centrorevision", targetNamespace = "")
        long centrorevision,
        @WebParam(name = "turno", targetNamespace = "")
        long turno,
        @WebParam(name = "urlturno", targetNamespace = "")
        String urlturno,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param idsolicitud
     * @param usuario
     * @param contrasenia
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "obtienePdfXReservaturno", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ObtienePdfXReservaturno")
    @ResponseWrapper(localName = "obtienePdfXReservaturnoResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ObtienePdfXReservaturnoResponse")
    public byte[] obtienePdfXReservaturno(
        @WebParam(name = "idsolicitud", targetNamespace = "")
        long idsolicitud,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param total
     * @param iva
     * @param alicuota
     * @param subtotal
     * @param identificacion
     * @param usuario
     * @param contrasenia
     * @param codigoservicio
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "generaOrdenpagoConvalor", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.GeneraOrdenpagoConvalor")
    @ResponseWrapper(localName = "generaOrdenpagoConvalorResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.GeneraOrdenpagoConvalorResponse")
    public String generaOrdenpagoConvalor(
        @WebParam(name = "identificacion", targetNamespace = "")
        String identificacion,
        @WebParam(name = "codigoservicio", targetNamespace = "")
        String codigoservicio,
        @WebParam(name = "subtotal", targetNamespace = "")
        String subtotal,
        @WebParam(name = "iva", targetNamespace = "")
        String iva,
        @WebParam(name = "alicuota", targetNamespace = "")
        String alicuota,
        @WebParam(name = "total", targetNamespace = "")
        String total,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param idsolicitud
     * @param usuario
     * @param contrasenia
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "obtienePdfXSolicitud", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ObtienePdfXSolicitud")
    @ResponseWrapper(localName = "obtienePdfXSolicitudResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.ObtienePdfXSolicitudResponse")
    public byte[] obtienePdfXSolicitud(
        @WebParam(name = "idsolicitud", targetNamespace = "")
        long idsolicitud,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

    /**
     * 
     * @param datos
     * @param usuario
     * @param contrasenia
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultado", targetNamespace = "")
    @RequestWrapper(localName = "registraOperadora", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.RegistraOperadora")
    @ResponseWrapper(localName = "registraOperadoraResponse", targetNamespace = "http://tc.portaltramite.com.ec", className = "ec.com.portaltramite.tc.RegistraOperadoraResponse")
    public String registraOperadora(
        @WebParam(name = "datos", targetNamespace = "")
        String datos,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia);

}
