package ec.com.portaltramite.tc;

import com.origami.sigef.common.config.CONFIG;
import ec.com.trafficcontrol.IntegracionPortalWS;
import java.net.URL;
import javax.ejb.Startup;
import javax.ejb.Stateless;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@Startup
@Stateless
@WebServiceClient(name = "TramitePortalWS", targetNamespace = "http://tc.portaltramite.com.ec", wsdlLocation = "/META-INF/wsdl/TramitePortalWS.wsdl")
public class TramitePortalWS
        extends Service {

    private final static URL TRAMITEPORTALWS_WSDL_LOCATION;
    private final static WebServiceException TRAMITEPORTALWS_EXCEPTION;
    private final static QName TRAMITEPORTALWS_QNAME = new QName("http://tc.portaltramite.com.ec", "TramitePortalWS");

    static {
        URL url = null;
        WebServiceException e = null;
        System.out.println("///////STATIC");
        try {
            System.out.println("///////RUTE WSDL: " + CONFIG.IP_TC_WEB);
            url = TramitePortalWS.class.getResource("/META-INF/wsdl/TramitePortalWS.wsdl");
            System.out.println("///////OUT URL: " + url);
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        TRAMITEPORTALWS_WSDL_LOCATION = url;
        TRAMITEPORTALWS_EXCEPTION = e;
    }

    public TramitePortalWS() {
        super(__getWsdlLocation(), TRAMITEPORTALWS_QNAME);
    }

    public TramitePortalWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRAMITEPORTALWS_QNAME, features);
    }

    public TramitePortalWS(URL wsdlLocation) {
        super(wsdlLocation, TRAMITEPORTALWS_QNAME);
    }

    public TramitePortalWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRAMITEPORTALWS_QNAME, features);
    }

    public TramitePortalWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TramitePortalWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns MetodosPort
     */
    @WebEndpoint(name = "MetodosPort")
    public MetodosPort getMetodosPort() {
        return super.getPort(new QName("http://tc.portaltramite.com.ec", "MetodosPort"), MetodosPort.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns MetodosPort
     */
    @WebEndpoint(name = "MetodosPort")
    public MetodosPort getMetodosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tc.portaltramite.com.ec", "MetodosPort"), MetodosPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRAMITEPORTALWS_EXCEPTION != null) {
            throw TRAMITEPORTALWS_EXCEPTION;
        }
        return TRAMITEPORTALWS_WSDL_LOCATION;
    }

}
